/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VentanaVerDiagramasRadiacion.java
 *
 * Created on 08-nov-2011, 0:35:35
 */
package Vista.ventanas.RAN.Components.antenas;

import Controlador.ControladorGeneral;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.AffineTransform;
import java.awt.geom.Ellipse2D;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author User
 */
public class VentanaVerDiagramasRadiacion extends javax.swing.JDialog {

    private ControladorGeneral controlador;
    private GraficaRadiacionHorizontal graficaRadiacionHorizontal;
    private GraficaRadiacionVertical graficaRadiacionVertical;
    
    /** Creates new form VentanaVerDiagramasRadiacion */
    public VentanaVerDiagramasRadiacion(java.awt.Frame parent, boolean modal, ControladorGeneral controlador, String valorAzimut, String valorElevacion) {
        super(parent, modal);
        this.controlador = controlador;
        
        graficaRadiacionHorizontal = new GraficaRadiacionHorizontal();
        graficaRadiacionHorizontal.setBounds(0, 0, 220, 220);
        
        graficaRadiacionVertical = new GraficaRadiacionVertical();
        graficaRadiacionVertical.setBounds(0, 0, 220, 220);
        
        initComponents();
        
        anguloAzimut.setText(valorAzimut);
        anguloElevacion.setText(valorElevacion);
        
    }
    
    public class GraficaRadiacionHorizontal extends JLabel{
        public void paint( Graphics g ) {
            Graphics2D g2d = (Graphics2D) g;
            ImageIcon iconoAguja = new ImageIcon("src/Images/Imagenes Grandes/test.png");
            
            g2d.setStroke(new BasicStroke(3.0f));
            g2d.setColor(new Color(255,0,0));
            g2d.rotate(Math.toRadians(Double.parseDouble(anguloAzimut.getText())), 126, 126);
            g2d.drawLine(126, 126, 126, 32);
        }
    }
    
    public class GraficaRadiacionVertical  extends JLabel {
        public void paint( Graphics g ) {
            Graphics2D g2d = (Graphics2D) g;
            ImageIcon iconoAguja = new ImageIcon("src/Images/Imagenes Grandes/test.png");
            
            g2d.setStroke(new BasicStroke(3.0f));
            g2d.setColor(new Color(0,0,255));
            g2d.rotate(Math.toRadians(Double.parseDouble(anguloElevacion.getText())-90), 142, 126);
            g2d.drawLine(142, 126, 142, 32);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelApuntamientoHorizontal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        anguloAzimut = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        panelApuntamientoVertical = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        anguloElevacion = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        botonAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Apuntamiento de la Antena");

        panelApuntamientoHorizontal.setBorder(javax.swing.BorderFactory.createTitledBorder("Apuntamiento Horizontal de Antena"));
        panelApuntamientoHorizontal.setName("panelApuntamientoHorizontal"); // NOI18N
        panelApuntamientoHorizontal.setLayout(null);
        panelApuntamientoHorizontal.add(graficaRadiacionHorizontal);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Imagenes Grandes/Diagrama de Radiacion Horizontal.png"))); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        panelApuntamientoHorizontal.add(jLabel1);
        jLabel1.setBounds(16, 16, 220, 220);

        jLabel3.setText("Angulo Azimut:");
        jLabel3.setName("jLabel3"); // NOI18N
        panelApuntamientoHorizontal.add(jLabel3);
        jLabel3.setBounds(26, 249, 72, 17);

        anguloAzimut.setEditable(false);
        anguloAzimut.setName("anguloAzimut"); // NOI18N
        panelApuntamientoHorizontal.add(anguloAzimut);
        anguloAzimut.setBounds(102, 247, 69, 20);

        jLabel4.setText("[º]");
        jLabel4.setName("jLabel4"); // NOI18N
        panelApuntamientoHorizontal.add(jLabel4);
        jLabel4.setBounds(175, 249, 13, 17);

        panelApuntamientoVertical.setBorder(javax.swing.BorderFactory.createTitledBorder("Apuntamiento Vertical de Antena"));
        panelApuntamientoVertical.add(graficaRadiacionVertical);
        panelApuntamientoVertical.setName("panelApuntamientoVertical"); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Imagenes Grandes/Diagrama de Radiacion Vertical.png"))); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel5.setText("[º]");
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setText("Angulo Elevacion:");
        jLabel6.setName("jLabel6"); // NOI18N

        anguloElevacion.setEditable(false);
        anguloElevacion.setName("anguloElevacion"); // NOI18N

        javax.swing.GroupLayout panelApuntamientoVerticalLayout = new javax.swing.GroupLayout(panelApuntamientoVertical);
        panelApuntamientoVertical.setLayout(panelApuntamientoVerticalLayout);
        panelApuntamientoVerticalLayout.setHorizontalGroup(
            panelApuntamientoVerticalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelApuntamientoVerticalLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
            .addGroup(panelApuntamientoVerticalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(anguloElevacion, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelApuntamientoVerticalLayout.setVerticalGroup(
            panelApuntamientoVerticalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelApuntamientoVerticalLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(panelApuntamientoVerticalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anguloElevacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setName("jPanel3"); // NOI18N

        botonAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/tick.png"))); // NOI18N
        botonAceptar.setText(" Cerrar");
        botonAceptar.setName("botonAceptar"); // NOI18N
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(355, Short.MAX_VALUE)
                .addComponent(botonAceptar))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelApuntamientoHorizontal, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelApuntamientoVertical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelApuntamientoHorizontal, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                    .addComponent(panelApuntamientoVertical, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        // TODO add your handling code here:
        //controlador.getControladorVentanas().editarENodeB(listaeNodeB.getSelectedItem().toString(), nombreENodeB.getText(), listaSitios.getSelectedItem().toString(), actualNombreRAN, listaRANs.getSelectedItem().toString(), Double.parseDouble(alturaTorre.getValue().toString()), tiposTorre.getSelectedItem().toString());
        this.dispose();
}//GEN-LAST:event_botonAceptarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anguloAzimut;
    private javax.swing.JTextField anguloElevacion;
    private javax.swing.JButton botonAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel panelApuntamientoHorizontal;
    private javax.swing.JPanel panelApuntamientoVertical;
    // End of variables declaration//GEN-END:variables
}
