/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VentanaNuevaAntena.java
 *
 * Created on 31/08/2011, 10:28:03 PM
 */
package Vista.ventanas.RAN.Components.antenas;

import Controlador.ControladorGeneral;
import Libreria.CentrarScreen;
import Modelo.PRO.Proyecto;
import Modelo.RAN.Antena;
import Modelo.RAN.ENodeB;
import java.util.Iterator;
import java.util.LinkedList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class VentanaGestionAntenas extends javax.swing.JDialog {

    private ControladorGeneral controlador;
    private String arrayRANs[];
    private String eNodosB[];
    private String nombreRANActual;
    
    /** Creates new form VentanaNuevaAntena */
    public VentanaGestionAntenas(java.awt.Frame parent, boolean modal, ControladorGeneral controlador) {
        super(parent, modal);
        this.controlador = controlador;
        initComponents();
        
        String proyectoPredeterminado = controlador.getLibroDeProyectos().getProyectoPredeterminado();
        LinkedList <Proyecto> proyectos = controlador.getLibroDeProyectos().getProyectos();
        
        for(int i = 0; i < proyectos.size(); i++){
            
            if(proyectos.get(i).getNombre().equals(proyectoPredeterminado)){
                
                arrayRANs = new String [proyectos.get(i).getGrupoRANs().size()];
                for(int j = 0; j < proyectos.get(i).getGrupoRANs().size(); j++){
                    arrayRANs[j] = proyectos.get(i).getGrupoRANs().get(j).getNombre();
                }
            }
        }
        try{
            nombreRAN.setModel(new DefaultComboBoxModel(arrayRANs));
        }catch(NullPointerException NPE){
            JOptionPane.showMessageDialog(null, "'No exiten sitios en el proyecto predeterminado'","Error 001: NullPointerException",JOptionPane.ERROR_MESSAGE);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        botonNuevaAntena = new javax.swing.JButton();
        botonEliminarAntena = new javax.swing.JButton();
        botonEditarAntena = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        nombreRAN = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        nombreENodeB = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAntenas = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        eNodeBActual = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        botonAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestion de Antenas");
        setIconImage(new ImageIcon("src/Images/iconos16x16/satellite_dish.png").getImage());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setName("jPanel5"); // NOI18N

        jSeparator4.setName("jSeparator4"); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos32x32/satellite_dish.png"))); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("Asistente para la Gestion de Antenas");
        jLabel2.setName("jLabel2"); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(379, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)))
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setRollover(true);
        jToolBar1.setName("jToolBar1"); // NOI18N

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos32x32/find.png"))); // NOI18N
        jButton2.setMnemonic('E');
        jButton2.setToolTipText("Encontrar...");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setName("jButton2"); // NOI18N
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jSeparator1.setName("jSeparator1"); // NOI18N
        jToolBar1.add(jSeparator1);

        botonNuevaAntena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos32x32/page_white_add.png"))); // NOI18N
        botonNuevaAntena.setToolTipText("Crear Nueva Antena");
        botonNuevaAntena.setEnabled(false);
        botonNuevaAntena.setName("botonNuevaAntena"); // NOI18N
        botonNuevaAntena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevaAntenaActionPerformed(evt);
            }
        });
        jToolBar1.add(botonNuevaAntena);

        botonEliminarAntena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos32x32/page_white_delete.png"))); // NOI18N
        botonEliminarAntena.setToolTipText("Eliminar Antena");
        botonEliminarAntena.setEnabled(false);
        botonEliminarAntena.setName("botonEliminarAntena"); // NOI18N
        botonEliminarAntena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarAntenaActionPerformed(evt);
            }
        });
        jToolBar1.add(botonEliminarAntena);

        botonEditarAntena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos32x32/page_white_edit.png"))); // NOI18N
        botonEditarAntena.setToolTipText("Editar Antena");
        botonEditarAntena.setEnabled(false);
        botonEditarAntena.setName("botonEditarAntena"); // NOI18N
        botonEditarAntena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarAntenaActionPerformed(evt);
            }
        });
        jToolBar1.add(botonEditarAntena);

        jPanel2.add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 40));

        jSeparator2.setName("jSeparator2"); // NOI18N
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 620, 10));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Panel de Busqueda"));
        jPanel1.setName("jPanel1"); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/find.png"))); // NOI18N
        jButton1.setText(" Encontrar");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Radio Access Network:");
        jLabel3.setName("jLabel3"); // NOI18N

        nombreRAN.setName("nombreRAN"); // NOI18N
        nombreRAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreRANActionPerformed(evt);
            }
        });

        jLabel4.setText("eNodeB:");
        jLabel4.setName("jLabel4"); // NOI18N

        nombreENodeB.setName("nombreENodeB"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreRAN, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreENodeB, 0, 197, Short.MAX_VALUE))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreRAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreENodeB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 600, 80));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Panel de Parametros de Antenas"));
        jPanel3.setName("jPanel3"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tablaAntenas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tipo de Antena", "Ganancia Maxima [dBi]", "Frecuancia Min. [MHz]", "Frecuencia Max. [MHz]", "HPBW Horizontal [º]", "Impedancia [Ω]", "Polarizacion", "Angulo Azimut [º]", "Angulo Elevación [º]"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaAntenas.setToolTipText("Tabla Antenas");
        tablaAntenas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tablaAntenas.setGridColor(new java.awt.Color(204, 204, 204));
        tablaAntenas.setName("tablaAntenas"); // NOI18N
        jScrollPane1.setViewportView(tablaAntenas);
        tablaAntenas.getColumnModel().getColumn(0).setPreferredWidth(110);
        tablaAntenas.getColumnModel().getColumn(1).setPreferredWidth(120);
        tablaAntenas.getColumnModel().getColumn(2).setPreferredWidth(130);
        tablaAntenas.getColumnModel().getColumn(3).setPreferredWidth(130);
        tablaAntenas.getColumnModel().getColumn(4).setPreferredWidth(130);
        tablaAntenas.getColumnModel().getColumn(5).setPreferredWidth(110);
        tablaAntenas.getColumnModel().getColumn(6).setPreferredWidth(90);
        tablaAntenas.getColumnModel().getColumn(7).setPreferredWidth(90);
        tablaAntenas.getColumnModel().getColumn(8).setPreferredWidth(100);
        tablaAntenas.getColumnModel().getColumn(9).setPreferredWidth(110);

        jLabel5.setText("eNodeB:");
        jLabel5.setName("jLabel5"); // NOI18N

        eNodeBActual.setEditable(false);
        eNodeBActual.setName("eNodeBActual"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eNodeBActual, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(eNodeBActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 600, 190));

        jTabbedPane1.addTab("Panel de Gestion de Antenas", jPanel2);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.setName("jPanel4"); // NOI18N

        botonAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/tick.png"))); // NOI18N
        botonAceptar.setText(" Cerrar");
        botonAceptar.setName("botonAceptar"); // NOI18N
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(529, Short.MAX_VALUE)
                .addComponent(botonAceptar))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addGap(9, 9, 9)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        // TODO add your handling code here:
        //controlador.getControladorVentanas().editarENodeB(listaeNodeB.getSelectedItem().toString(), nombreENodeB.getText(), listaSitios.getSelectedItem().toString(), actualNombreRAN, listaRANs.getSelectedItem().toString(), Double.parseDouble(alturaTorre.getValue().toString()), tiposTorre.getSelectedItem().toString());
        this.dispose();
}//GEN-LAST:event_botonAceptarActionPerformed

    private void botonNuevaAntenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevaAntenaActionPerformed
        // TODO add your handling code here:
        controlador.getControladorVentanas().crearVentanaNuevaAntena(controlador, nombreRAN.getSelectedItem().toString(), nombreENodeB.getSelectedItem().toString());
    }//GEN-LAST:event_botonNuevaAntenaActionPerformed

    private void nombreRANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreRANActionPerformed
        // TODO add your handling code here:
        
        String RANSeleccionada = nombreRAN.getSelectedItem().toString();
        String proyectoPredeterminado = controlador.getLibroDeProyectos().getProyectoPredeterminado();
        LinkedList <Proyecto> proyectos = controlador.getLibroDeProyectos().getProyectos();
        
        for(int i = 0; i < proyectos.size(); i++){
            
            if(proyectos.get(i).getNombre().equals(proyectoPredeterminado)){
                
                for(int j = 0; j < proyectos.get(i).getGrupoRANs().size(); j++){
                    if(proyectos.get(i).getGrupoRANs().get(j).getNombre().equals(RANSeleccionada)){
                        
                        LinkedList <ENodeB> grupoNodos = proyectos.get(i).getGrupoRANs().get(j).getGrupoNodosB();
                        eNodosB = new String [grupoNodos.size()];
                        for(int k = 0; k < grupoNodos.size(); k++){
                            eNodosB[k] = grupoNodos.get(k).getNombre();
                            nombreENodeB.setModel(new DefaultComboBoxModel(eNodosB));
                        }
                        if(grupoNodos.size() == 0){
                            eNodosB = new String [0];
                            nombreENodeB.setModel(new DefaultComboBoxModel(eNodosB));
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_nombreRANActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        encontrarENodeB();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        encontrarENodeB();
    }//GEN-LAST:event_jButton2ActionPerformed

private void botonEditarAntenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarAntenaActionPerformed
// TODO add your handling code here:
    try{
        VentanaEditarAntena ventana = new VentanaEditarAntena(new JFrame(), true, controlador, nombreRANActual ,eNodeBActual.getText(), getFilaSeleccionada());
        CentrarScreen.centrarVentana(ventana);
        ventana.setVisible(true);
    }catch(ArrayIndexOutOfBoundsException AIE){
        JOptionPane.showMessageDialog(null, "'No ha seleccionado ninguna Antena'","Error 004: NullPointerException",JOptionPane.ERROR_MESSAGE);
    }
}//GEN-LAST:event_botonEditarAntenaActionPerformed

private void botonEliminarAntenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarAntenaActionPerformed
// TODO add your handling code here:
    try{
        VentanaEliminarAntena ventana = new VentanaEliminarAntena(new JFrame(), true, controlador, nombreRANActual ,eNodeBActual.getText(), getFilaSeleccionada());
        CentrarScreen.centrarVentana(ventana);
        ventana.setVisible(true);
    }catch(ArrayIndexOutOfBoundsException AIE){
        JOptionPane.showMessageDialog(null, "'No ha seleccionado ninguna Antena'","Error 004: NullPointerException",JOptionPane.ERROR_MESSAGE);
    }
}//GEN-LAST:event_botonEliminarAntenaActionPerformed

    private void encontrarENodeB(){
        String RANSeleccionada;

        try{
        
        RANSeleccionada = nombreRAN.getSelectedItem().toString();
        
        String proyectoPredeterminado = controlador.getLibroDeProyectos().getProyectoPredeterminado();
        LinkedList <Proyecto> proyectos = controlador.getLibroDeProyectos().getProyectos();
        
            if(!nombreENodeB.getSelectedItem().toString().equals("")){
                for(int i = 0; i < proyectos.size(); i++){

                    if(proyectos.get(i).getNombre().equals(proyectoPredeterminado)){

                        for(int j = 0; j < proyectos.get(i).getGrupoRANs().size(); j++){
                            if(proyectos.get(i).getGrupoRANs().get(j).getNombre().equals(RANSeleccionada)){

                                LinkedList <ENodeB> grupoNodos = proyectos.get(i).getGrupoRANs().get(j).getGrupoNodosB();
                                for(int k = 0; k < grupoNodos.size(); k++){
                                    if(grupoNodos.get(k).getNombre().equals(nombreENodeB.getSelectedItem().toString())){
                                        botonNuevaAntena.setEnabled(true);
                                        botonEliminarAntena.setEnabled(true);
                                        botonEditarAntena.setEnabled(true);
                                        nombreRANActual = RANSeleccionada;
                                        
                                        eNodeBActual.setText(grupoNodos.get(k).getNombre());
                                        actualizarTablaAntenas(grupoNodos.get(k).getAntenas());
                                    }
                                }
                            }
                        }
                    }
                }
            }else{
                eNodeBActual.setText("");
                botonNuevaAntena.setEnabled(false);
            }
        }catch(NullPointerException NPE){
            eNodeBActual.setText("");
            botonNuevaAntena.setEnabled(false);
            botonEliminarAntena.setEnabled(false);
            botonEditarAntena.setEnabled(false);
            
            JOptionPane.showMessageDialog(null, "'No exite ningun ENodeB creado para la RAN: " + nombreRAN.getSelectedItem().toString() + "'","Error 003: NullPointerException",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void actualizarTablaAntenas(LinkedList <Antena> antenas) {
        
        Object[][] parametros = new Object[antenas.size()][10];
        
        String[] columnas = new String [] {
                "Nombre", "Tipo de Antena", "Ganancia Maxima [dBi]", "Frecuancia Min. [MHz]", "Frecuencia Max. [MHz]", 
                "HPBW Horizontal [º]", "Impedancia [Ω]", "Polarizacion","Angulo Azimut [º]", "Angulo Elevación [º]"
            };
        
        for(int j = 0; j < antenas.size(); j++){
            
            parametros[j][0] = antenas.get(j).getNombreAntena();    parametros[j][1] = antenas.get(j).getTipoAntena();
            parametros[j][2] = antenas.get(j).getGananciaMaxima();  parametros[j][3] = antenas.get(j).getFrecuenciaMinima();
            parametros[j][4] = antenas.get(j).getFrecuenciaMaxima();parametros[j][5] = antenas.get(j).getHPBW_Horizantal();
            parametros[j][6] = antenas.get(j).getImpedancia();      parametros[j][7] = antenas.get(j).getPolarizacion();
            parametros[j][8] = antenas.get(j).getAnguloAzimut();    parametros[j][9] = antenas.get(j).getAnguloElevacion();
        }
        DefaultTableModel modelo = new DefaultTableModel(parametros, columnas);
        tablaAntenas.setModel(modelo);
        
        tablaAntenas.getColumnModel().getColumn(0).setPreferredWidth(110);tablaAntenas.getColumnModel().getColumn(1).setPreferredWidth(120); 
        tablaAntenas.getColumnModel().getColumn(2).setPreferredWidth(130);tablaAntenas.getColumnModel().getColumn(3).setPreferredWidth(130);
        tablaAntenas.getColumnModel().getColumn(4).setPreferredWidth(130);tablaAntenas.getColumnModel().getColumn(5).setPreferredWidth(110);
        tablaAntenas.getColumnModel().getColumn(6).setPreferredWidth(90); tablaAntenas.getColumnModel().getColumn(7).setPreferredWidth(90);
        tablaAntenas.getColumnModel().getColumn(8).setPreferredWidth(100);tablaAntenas.getColumnModel().getColumn(9).setPreferredWidth(110);
        tablaAntenas.setEnabled(true);
    }
    
    public String getFilaSeleccionada()
    {
          return (String) tablaAntenas.getValueAt(tablaAntenas.getSelectedRow(), 0).toString();
    }
    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonEditarAntena;
    private javax.swing.JButton botonEliminarAntena;
    private javax.swing.JButton botonNuevaAntena;
    private javax.swing.JTextField eNodeBActual;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JComboBox nombreENodeB;
    private javax.swing.JComboBox nombreRAN;
    private javax.swing.JTable tablaAntenas;
    // End of variables declaration//GEN-END:variables

}
