/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VentanaNuevoSitio.java
 *
 * Created on 27/07/2011, 08:30:02 PM
 */
package Vista.ventanas.RAN.OutdoorLink;

import Vista.ventanas.Sitio.*;
import Controlador.ControladorGeneral;
import Libreria.CentrarScreen;
import Modelo.MOVIL.EquipoUsuario;
import Modelo.PRO.Proyecto;
import Modelo.PRO.Sitio;
import Modelo.RAN.ENodeB;
import Modelo.RAN.Radio;
import Modelo.SIM.Outdoor.OutdoorLink;
import Modelo.SIM.Outdoor.OutdoorLinkRAN;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class VentanaNuevoOutdoorLink extends javax.swing.JDialog {

    private ControladorGeneral controlador;
    
    /** Creates new form VentanaNuevoSitio */
    public VentanaNuevoOutdoorLink(java.awt.Frame parent, boolean modal, ControladorGeneral controlador) {
        super(parent, modal);
        this.controlador = controlador;
        initComponents();
        
        String[] arrayNombresRAN = null;
        String[] arrayNombresEU = null;
        LinkedList<Proyecto> proyectos = controlador.getLibroDeProyectos().getProyectos();
        String proyectoPredeterminadoActual = controlador.getLibroDeProyectos().getProyectoPredeterminado();
        for(int i=0; i < proyectos.size(); i++){
            //si el proyecto es predeterminado
             if(proyectos.get(i).getNombre().equals(proyectoPredeterminadoActual)){
                 arrayNombresRAN = new String[proyectos.get(i).getGrupoRANs().size()];
                 for(int j=0; j < proyectos.get(i).getGrupoRANs().size(); j++){
                     arrayNombresRAN[j] = proyectos.get(i).getGrupoRANs().get(j).getNombre();
                 }
                 arrayNombresEU = new String[proyectos.get(i).getGrupoEUs().size()];
                 for(int j=0; j < proyectos.get(i).getGrupoEUs().size(); j++){
                     arrayNombresEU[j] = proyectos.get(i).getGrupoEUs().get(j).getNombreEstacionMovil();
                 }
             }
        }
        try{
            RAN.setModel(new DefaultComboBoxModel(arrayNombresRAN));
        }catch(NullPointerException NPE){
            JOptionPane.showMessageDialog(null,"'No exiten ningun proyecto predeterminado'","Error 008: NullPointerException",JOptionPane.ERROR_MESSAGE);
        }
        try{
            equipoUsuario.setModel(new DefaultComboBoxModel(arrayNombresEU));
        }catch(NullPointerException NPE){
            //JOptionPane.showMessageDialog(null,"'No exiten ningun proyecto predeterminado'","Error 009: NullPointerException",JOptionPane.ERROR_MESSAGE);
        }
        
        tipoEnlace.setModel(new DefaultComboBoxModel(OutdoorLink.TIPOS_OUTDOOR_LINK_REDMOVIL));
        tipoEnlace.setSelectedItem("Uu");
        tecnologiaEnlace.setModel(new DefaultComboBoxModel(OutdoorLinkRAN.TECNOLOGIAS_OUTDOOR_LINK_RAN));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        nombreOutdoorLink = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tipoEnlace = new javax.swing.JComboBox();
        tecnologiaEnlace = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        botonAceptar = new javax.swing.JButton();
        botonCanelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        equipoUsuario = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        tecnologiaEstacionMovil = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        indoorLink = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        RAN = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        eNodeB = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        tecnologiasEstacionBase = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nueva Conexion Outdoor");
        setIconImage(new ImageIcon("src/Images/iconos16x16/connect-add.png").getImage());
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setName("jPanel3"); // NOI18N

        jSeparator2.setName("jSeparator2"); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos32x32/connect-add.png"))); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Asistente para la creacion de un nueva Conexión Outdoor");
        jLabel2.setName("jLabel2"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(215, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacion General"));
        jPanel2.setName("jPanel2"); // NOI18N

        jLabel5.setText("Nombre del Enlace Outdoor:");
        jLabel5.setName("jLabel5"); // NOI18N

        nombreOutdoorLink.setName("nombreOutdoorLink"); // NOI18N

        jLabel4.setText("Tipo de Enlace:");
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel9.setText("Tecnologia del Enlace:");
        jLabel9.setName("jLabel9"); // NOI18N

        tipoEnlace.setName("tipoEnlace"); // NOI18N
        tipoEnlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoEnlaceActionPerformed(evt);
            }
        });

        tecnologiaEnlace.setName("tecnologiaEnlace"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreOutdoorLink, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tipoEnlace, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(2, 2, 2)
                        .addComponent(tecnologiaEnlace, 0, 210, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreOutdoorLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tipoEnlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tecnologiaEnlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.setName("jPanel4"); // NOI18N

        botonAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/tick.png"))); // NOI18N
        botonAceptar.setText(" Aceptar");
        botonAceptar.setName("botonAceptar"); // NOI18N
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        botonCanelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/cross-script.png"))); // NOI18N
        botonCanelar.setText(" Cancelar");
        botonCanelar.setName("botonCanelar"); // NOI18N
        botonCanelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCanelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(335, Short.MAX_VALUE)
                .addComponent(botonCanelar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(botonCanelar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Estacion Movil"));
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel3.setText("Equipo de Usuario:");
        jLabel3.setName("jLabel3"); // NOI18N

        equipoUsuario.setName("equipoUsuario"); // NOI18N
        equipoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipoUsuarioActionPerformed(evt);
            }
        });

        jLabel10.setText("Tecnologia:");
        jLabel10.setName("jLabel10"); // NOI18N

        tecnologiaEstacionMovil.setEditable(false);
        tecnologiaEstacionMovil.setName("tecnologiaEstacionMovil"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(equipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tecnologiaEstacionMovil, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(equipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(tecnologiaEstacionMovil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Estacion Base"));
        jPanel6.setName("jPanel6"); // NOI18N

        jLabel6.setText("Enlace Indoor:");
        jLabel6.setName("jLabel6"); // NOI18N

        indoorLink.setName("indoorLink"); // NOI18N
        indoorLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indoorLinkActionPerformed(evt);
            }
        });

        jLabel7.setText("Radio Access Network:");
        jLabel7.setName("jLabel7"); // NOI18N

        RAN.setName("RAN"); // NOI18N
        RAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RANActionPerformed(evt);
            }
        });

        jLabel8.setText("eNodeB:");
        jLabel8.setName("jLabel8"); // NOI18N

        eNodeB.setName("eNodeB"); // NOI18N
        eNodeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eNodeBActionPerformed(evt);
            }
        });

        jLabel11.setText("Tecnologia:");
        jLabel11.setName("jLabel11"); // NOI18N

        tecnologiasEstacionBase.setEditable(false);
        tecnologiasEstacionBase.setName("tecnologiasEstacionBase"); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RAN, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(indoorLink, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tecnologiasEstacionBase, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(eNodeB, 0, 200, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(RAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eNodeB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(indoorLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tecnologiasEstacionBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
       
        try{
            if(!nombreOutdoorLink.getText().equals("")&&!equipoUsuario.getSelectedItem().toString().equals("")&&!indoorLink.getSelectedItem().toString().equals("")){
                if(tecnologiaEnlace.getSelectedItem().toString().equals(tecnologiaEstacionMovil.getText())&&tecnologiaEnlace.getSelectedItem().toString().equals(tecnologiasEstacionBase.getText())){
                    controlador.getControladorVentanas().crearNuevoOutdoorLink(nombreOutdoorLink.getText(), tipoEnlace.getSelectedItem().toString(), tecnologiaEnlace.getSelectedItem().toString(),
                            equipoUsuario.getSelectedItem().toString(), RAN.getSelectedItem().toString(), eNodeB.getSelectedItem().toString(), indoorLink.getSelectedItem().toString());
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(null, "'Existe incompatibilidad de tecnologias'","Error 010: Inconsistencia de Parametros",JOptionPane.ERROR_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(null, "'Existen campos vacio o valores incorrectos'","Error 002: NullPointerException",JOptionPane.ERROR_MESSAGE);
            }
        }catch(NullPointerException NPE){
            JOptionPane.showMessageDialog(null, "'Existen campos vacio o valores incorrectos'","Error 002: NullPointerException",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void botonCanelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCanelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
}//GEN-LAST:event_botonCanelarActionPerformed

private void tipoEnlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoEnlaceActionPerformed
// TODO add your handling code here:
    if(!tipoEnlace.getSelectedItem().equals("Uu")){
        equipoUsuario.setEnabled(false);
        tecnologiaEnlace.setEnabled(false);
        RAN.setEnabled(false);
        eNodeB.setEnabled(false);
        indoorLink.setEnabled(false);
        
        equipoUsuario.setModel(new DefaultComboBoxModel());
        tecnologiaEnlace.setModel(new DefaultComboBoxModel());
        RAN.setModel(new DefaultComboBoxModel());
        eNodeB.setModel(new DefaultComboBoxModel());
        indoorLink.setModel(new DefaultComboBoxModel()); 
    }else if(tipoEnlace.getSelectedItem().equals("Uu")){
        
        equipoUsuario.setEnabled(true);
        tecnologiaEnlace.setEnabled(true);
        RAN.setEnabled(true);
        eNodeB.setEnabled(true);
        indoorLink.setEnabled(true);
        
        tipoEnlace.setModel(new DefaultComboBoxModel(OutdoorLink.TIPOS_OUTDOOR_LINK_REDMOVIL));
        tecnologiaEnlace.setModel(new DefaultComboBoxModel(OutdoorLinkRAN.TECNOLOGIAS_OUTDOOR_LINK_RAN));
        
        String[] arrayNombresRAN = null;
        String[] arrayNombresEU = null;
        LinkedList<Proyecto> proyectos = controlador.getLibroDeProyectos().getProyectos();
        String proyectoPredeterminadoActual = controlador.getLibroDeProyectos().getProyectoPredeterminado();
        for(int i=0; i < proyectos.size(); i++){
            //si el proyecto es predeterminado
             if(proyectos.get(i).getNombre().equals(proyectoPredeterminadoActual)){
                 arrayNombresRAN = new String[proyectos.get(i).getGrupoRANs().size()];
                 for(int j=0; j < proyectos.get(i).getGrupoRANs().size(); j++){
                     arrayNombresRAN[j] = proyectos.get(i).getGrupoRANs().get(j).getNombre();
                 }
                 arrayNombresEU = new String[proyectos.get(i).getGrupoEUs().size()];
                 for(int j=0; j < proyectos.get(i).getGrupoEUs().size(); j++){
                     arrayNombresEU[j] = proyectos.get(i).getGrupoEUs().get(j).getNombreEstacionMovil();
                 }
             }
        }
        try{RAN.setModel(new DefaultComboBoxModel(arrayNombresRAN));}catch(NullPointerException NPE){}
        try{equipoUsuario.setModel(new DefaultComboBoxModel(arrayNombresEU));}catch(NullPointerException NPE){}
    }
}//GEN-LAST:event_tipoEnlaceActionPerformed

private void equipoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipoUsuarioActionPerformed
// TODO add your handling code here:
        LinkedList<Proyecto> proyectos = controlador.getLibroDeProyectos().getProyectos();
        String proyectoPredeterminadoActual = controlador.getLibroDeProyectos().getProyectoPredeterminado();
        for(int i=0; i < proyectos.size(); i++){
            //si el proyecto es predeterminado
             if(proyectos.get(i).getNombre().equals(proyectoPredeterminadoActual)){
                 for(int j=0; j < proyectos.get(i).getGrupoEUs().size(); j++){
                     if(proyectos.get(i).getGrupoEUs().get(j).getNombreEstacionMovil().equals(equipoUsuario.getSelectedItem().toString())){
                         tecnologiaEstacionMovil.setText(proyectos.get(i).getGrupoEUs().get(j).getTecnlogia());
                     }
                 }
             }
        }
    
}//GEN-LAST:event_equipoUsuarioActionPerformed

private void RANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RANActionPerformed
// TODO add your handling code here:
    
    String[] listaNodos = null;
    LinkedList<Proyecto> proyectos = controlador.getLibroDeProyectos().getProyectos();
    String proyectoPredeterminadoActual = controlador.getLibroDeProyectos().getProyectoPredeterminado();
        for(int i=0; i < proyectos.size(); i++){
            //si el proyecto es predeterminado
             if(proyectos.get(i).getNombre().equals(proyectoPredeterminadoActual)){
                 for(int j=0; j < proyectos.get(i).getGrupoRANs().size(); j++){
                     if(proyectos.get(i).getGrupoRANs().get(j).getNombre().equals(RAN.getSelectedItem().toString())){
                         LinkedList<ENodeB> nodos = proyectos.get(i).getGrupoRANs().get(j).getGrupoNodosB();
                         listaNodos = new String[nodos.size()];
                         for(int k=0; k < nodos.size(); k++){
                             listaNodos[k] = nodos.get(k).getNombre();
                         }
                     }
                 }
             }
        }
        eNodeB.setModel(new DefaultComboBoxModel(listaNodos)); 
}//GEN-LAST:event_RANActionPerformed

private void eNodeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eNodeBActionPerformed
// TODO add your handling code here:
    
    String[] listaEnlacesIndoor = null;
    LinkedList<Proyecto> proyectos = controlador.getLibroDeProyectos().getProyectos();
    String proyectoPredeterminadoActual = controlador.getLibroDeProyectos().getProyectoPredeterminado();
        for(int i=0; i < proyectos.size(); i++){
            //si el proyecto es predeterminado
             if(proyectos.get(i).getNombre().equals(proyectoPredeterminadoActual)){
                 for(int j=0; j < proyectos.get(i).getGrupoRANs().size(); j++){
                     if(proyectos.get(i).getGrupoRANs().get(j).getNombre().equals(RAN.getSelectedItem().toString())){
                         LinkedList <ENodeB> listaNodos = proyectos.get(i).getGrupoRANs().get(j).getGrupoNodosB();
                         for(int k=0; k < listaNodos.size(); k++){
                             if(listaNodos.get(k).getNombre().equals(eNodeB.getSelectedItem().toString())){
                                 listaEnlacesIndoor = new String[listaNodos.get(k).getIndoorLinks().size()];
                                 for(int l=0; l< listaNodos.get(k).getIndoorLinks().size();l++){
                                     listaEnlacesIndoor[l] = listaNodos.get(k).getIndoorLinks().get(l).getNombreLink();
                                 }
                             }
                         }
                     }
                 }
             }
        }
        indoorLink.setModel(new DefaultComboBoxModel(listaEnlacesIndoor)); 
}//GEN-LAST:event_eNodeBActionPerformed

private void indoorLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indoorLinkActionPerformed
// TODO add your handling code here:
    String[] listaEnlacesIndoor = null;
    LinkedList<Proyecto> proyectos = controlador.getLibroDeProyectos().getProyectos();
    String proyectoPredeterminadoActual = controlador.getLibroDeProyectos().getProyectoPredeterminado();
        for(int i=0; i < proyectos.size(); i++){
            //si el proyecto es predeterminado
             if(proyectos.get(i).getNombre().equals(proyectoPredeterminadoActual)){
                 for(int j=0; j < proyectos.get(i).getGrupoRANs().size(); j++){
                     if(proyectos.get(i).getGrupoRANs().get(j).getNombre().equals(RAN.getSelectedItem().toString())){
                         LinkedList <ENodeB> listaNodos = proyectos.get(i).getGrupoRANs().get(j).getGrupoNodosB();
                         for(int k=0; k < listaNodos.size(); k++){
                             if(listaNodos.get(k).getNombre().equals(eNodeB.getSelectedItem().toString())){
                                 for(int l=0; l< listaNodos.get(k).getIndoorLinks().size();l++){
                                     if(listaNodos.get(k).getIndoorLinks().get(l).getNombreLink().equals(indoorLink.getSelectedItem().toString())){
                                         tecnologiasEstacionBase.setText(listaNodos.get(k).getIndoorLinks().get(l).getTargetaEquipoRadio().getTecnologia());
                                     }
                                 }
                             }
                         }
                     }
                 }
             }
        }
}//GEN-LAST:event_indoorLinkActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox RAN;
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCanelar;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JComboBox eNodeB;
    private javax.swing.JComboBox equipoUsuario;
    private javax.swing.JComboBox indoorLink;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField nombreOutdoorLink;
    private javax.swing.JComboBox tecnologiaEnlace;
    private javax.swing.JTextField tecnologiaEstacionMovil;
    private javax.swing.JTextField tecnologiasEstacionBase;
    private javax.swing.JComboBox tipoEnlace;
    // End of variables declaration//GEN-END:variables
}
