/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VentanaNuevoSitio.java
 *
 * Created on 27/07/2011, 08:30:02 PM
 */
package Vista.ventanas.Simulacion;

import Controlador.ControladorGeneral;
import Modelo.GEO.CoordenadaGeografica;
import Modelo.SIM.Outdoor.Paths.PathModelo_ITU_R_M2135;
import java.text.DecimalFormat;
import java.text.ParseException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;

/**
 *
 * @author Usuario
 */
public class VentanaNuevoPathModeloITU extends javax.swing.JDialog {

    private ControladorGeneral controlador;
    private double elevacion = 0;
    
    /** Creates new form VentanaNuevoSitio */
    public VentanaNuevoPathModeloITU(java.awt.Frame parent, boolean modal, ControladorGeneral controlador, double distanciaEnlaceEnTierra) {
        super(parent, modal);
        this.controlador = controlador;
        initComponents();
        
        buttonGroup.add(gradosMinutosSegundos);
        buttonGroup.add(decimal);
        
        tipoPath.setModel(new DefaultComboBoxModel(PathModelo_ITU_R_M2135.TIPOS_PATH1));
        tipoEscenario.setModel(new DefaultComboBoxModel(PathModelo_ITU_R_M2135.TIPOS_ESCENARIOS));
        rangoShadowing.setModel(new DefaultComboBoxModel(PathModelo_ITU_R_M2135.CASOS_SHADOWING));
        alturaPromedioEdificios.setEnabled(false);
        anchuraPromedioCalles.setEnabled(false);
        distrubucionUrbanistica.setModel(new DefaultComboBoxModel());
        
        distanciaEnlace.setText(""+distanciaEnlaceEnTierra);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        botonAceptar = new javax.swing.JButton();
        botonCanelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        numeroPath = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tipoEscenario = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        tipoPath = new javax.swing.JComboBox();
        botonProbabilidadLOS = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        distanciaEnlace = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        alturaPromedioEdificios = new javax.swing.JSpinner();
        anchuraPromedioCalles = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        distrubucionUrbanistica = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        temperaturaAmbiente = new javax.swing.JSpinner();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        latGrados = new javax.swing.JTextField();
        longGrados = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        latMinutos = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        longMinutos = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        longSegundos = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        latSegundos = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        hemisferioLat = new javax.swing.JComboBox();
        gradosMinutosSegundos = new javax.swing.JRadioButton();
        decimal = new javax.swing.JRadioButton();
        latGradosDecimal = new javax.swing.JTextField();
        longGradosDecimal = new javax.swing.JTextField();
        obtenerPunto = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        limpiarCampos = new javax.swing.JButton();
        hemisferioLong = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        anguloVectorUnitario = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        minimaProbabilidadShadowing = new javax.swing.JSpinner();
        jLabel29 = new javax.swing.JLabel();
        rangoShadowing = new javax.swing.JComboBox();
        jPanel7 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        cantidadGrupos = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nuevo Path");
        setIconImage(new ImageIcon("src/Images/iconos16x16/chart_line_add.png").getImage());
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setName("jPanel3"); // NOI18N

        jSeparator2.setName("jSeparator2"); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos32x32/chart_line_add.png"))); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("Asistente para la creacion de un nuevo Path");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Modelo ITU-R M.2135");
        jLabel3.setName("jLabel3"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(214, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.setName("jPanel4"); // NOI18N

        botonAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/tick.png"))); // NOI18N
        botonAceptar.setText(" Aceptar");
        botonAceptar.setName("botonAceptar"); // NOI18N
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        botonCanelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/cross-script.png"))); // NOI18N
        botonCanelar.setText(" Cancelar");
        botonCanelar.setName("botonCanelar"); // NOI18N
        botonCanelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCanelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(386, Short.MAX_VALUE)
                .addComponent(botonCanelar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(botonCanelar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacion General"));
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel4.setText("Numero de Path");
        jLabel4.setName("jLabel4"); // NOI18N

        numeroPath.setEditable(false);
        numeroPath.setFont(new java.awt.Font("Tahoma", 1, 11));
        numeroPath.setText("1");
        numeroPath.setName("numeroPath"); // NOI18N

        jLabel5.setText("Tipo de Escenario:");
        jLabel5.setName("jLabel5"); // NOI18N

        tipoEscenario.setName("tipoEscenario"); // NOI18N
        tipoEscenario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoEscenarioActionPerformed(evt);
            }
        });

        jLabel6.setText("Tipo de Path:");
        jLabel6.setName("jLabel6"); // NOI18N

        tipoPath.setName("tipoPath"); // NOI18N
        tipoPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoPathActionPerformed(evt);
            }
        });

        botonProbabilidadLOS.setText("Probabilidad de LOS");
        botonProbabilidadLOS.setName("botonProbabilidadLOS"); // NOI18N
        botonProbabilidadLOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonProbabilidadLOSActionPerformed(evt);
            }
        });

        jLabel30.setText("Disatancia Enlace:");
        jLabel30.setName("jLabel30"); // NOI18N

        distanciaEnlace.setEditable(false);
        distanciaEnlace.setName("distanciaEnlace"); // NOI18N

        jLabel31.setText("[m]");
        jLabel31.setName("jLabel31"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tipoPath, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(distanciaEnlace, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel31)
                        .addGap(18, 18, 18)
                        .addComponent(botonProbabilidadLOS, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numeroPath, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tipoEscenario, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numeroPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoEscenario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tipoPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(distanciaEnlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonProbabilidadLOS)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacion Urbanistica"));
        jPanel2.setName("jPanel2"); // NOI18N

        jLabel7.setText("Altura Promedio de Edificios:");
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel8.setText("Anchura Promedio de Calles:");
        jLabel8.setName("jLabel8"); // NOI18N

        alturaPromedioEdificios.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 150.0d, 0.5d));
        alturaPromedioEdificios.setEnabled(false);
        alturaPromedioEdificios.setName("alturaPromedioEdificios"); // NOI18N

        anchuraPromedioCalles.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 50.0d, 0.5d));
        anchuraPromedioCalles.setEnabled(false);
        anchuraPromedioCalles.setName("anchuraPromedioCalles"); // NOI18N

        jLabel10.setText("Distribucion Urbanistica:");
        jLabel10.setName("jLabel10"); // NOI18N

        distrubucionUrbanistica.setEnabled(false);
        distrubucionUrbanistica.setName("distrubucionUrbanistica"); // NOI18N
        distrubucionUrbanistica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distrubucionUrbanisticaActionPerformed(evt);
            }
        });

        jLabel23.setText("Temperatura Ambiente:");
        jLabel23.setName("jLabel23"); // NOI18N

        temperaturaAmbiente.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(19.0d), Double.valueOf(-10.0d), null, Double.valueOf(0.5d)));
        temperaturaAmbiente.setName("temperaturaAmbiente"); // NOI18N

        jLabel24.setText("[º C]");
        jLabel24.setName("jLabel24"); // NOI18N

        jLabel26.setText("[m]");
        jLabel26.setName("jLabel26"); // NOI18N

        jLabel27.setText("[m]");
        jLabel27.setName("jLabel27"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alturaPromedioEdificios, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(anchuraPromedioCalles, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel27))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(distrubucionUrbanistica, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(temperaturaAmbiente, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(alturaPromedioEdificios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(anchuraPromedioCalles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(distrubucionUrbanistica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(temperaturaAmbiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel23))
                .addGap(5, 5, 5))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Parametros Geograficos"));
        jPanel5.setName("jPanel5"); // NOI18N

        jLabel11.setText("Latitud:");
        jLabel11.setName("jLabel11"); // NOI18N

        jLabel12.setText("Longitud:");
        jLabel12.setName("jLabel12"); // NOI18N

        latGrados.setEditable(false);
        latGrados.setName("latGrados"); // NOI18N

        longGrados.setEditable(false);
        longGrados.setName("longGrados"); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel13.setText("º");
        jLabel13.setName("jLabel13"); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel14.setText("º");
        jLabel14.setName("jLabel14"); // NOI18N

        latMinutos.setEditable(false);
        latMinutos.setName("latMinutos"); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel15.setText("'");
        jLabel15.setName("jLabel15"); // NOI18N

        longMinutos.setEditable(false);
        longMinutos.setName("longMinutos"); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel16.setText("'");
        jLabel16.setName("jLabel16"); // NOI18N

        longSegundos.setEditable(false);
        longSegundos.setName("longSegundos"); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel17.setText("''");
        jLabel17.setName("jLabel17"); // NOI18N

        latSegundos.setEditable(false);
        latSegundos.setName("latSegundos"); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel18.setText("''");
        jLabel18.setName("jLabel18"); // NOI18N

        hemisferioLat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N", "S" }));
        hemisferioLat.setEnabled(false);
        hemisferioLat.setName("hemisferioLat"); // NOI18N

        gradosMinutosSegundos.setSelected(true);
        gradosMinutosSegundos.setText("Grados, Minutos y Segundos");
        gradosMinutosSegundos.setEnabled(false);
        gradosMinutosSegundos.setName("gradosMinutosSegundos"); // NOI18N
        gradosMinutosSegundos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradosMinutosSegundosActionPerformed(evt);
            }
        });

        decimal.setText("Decimal");
        decimal.setEnabled(false);
        decimal.setName("decimal"); // NOI18N
        decimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decimalActionPerformed(evt);
            }
        });

        latGradosDecimal.setEditable(false);
        latGradosDecimal.setName("latGradosDecimal"); // NOI18N

        longGradosDecimal.setEditable(false);
        longGradosDecimal.setName("longGradosDecimal"); // NOI18N

        obtenerPunto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/arrow-curve-270-left.png"))); // NOI18N
        obtenerPunto.setText("Obtener Punto");
        obtenerPunto.setEnabled(false);
        obtenerPunto.setName("obtenerPunto"); // NOI18N
        obtenerPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obtenerPuntoActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel19.setText("[º]");
        jLabel19.setName("jLabel19"); // NOI18N

        limpiarCampos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/eraser.png"))); // NOI18N
        limpiarCampos.setText(" Limpiar");
        limpiarCampos.setEnabled(false);
        limpiarCampos.setName("limpiarCampos"); // NOI18N
        limpiarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarCamposActionPerformed(evt);
            }
        });

        hemisferioLong.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "O", "E" }));
        hemisferioLong.setEnabled(false);
        hemisferioLong.setName("hemisferioLong"); // NOI18N

        jLabel9.setText("Angulo Vector Unitario respecto al Norte:");
        jLabel9.setName("jLabel9"); // NOI18N

        anguloVectorUnitario.setModel(new javax.swing.SpinnerNumberModel(0.0d, -180.0d, 180.0d, 0.5d));
        anguloVectorUnitario.setToolTipText("Angulo en grados del vector normal de la pared (entre -180º y 180º)");
        anguloVectorUnitario.setEnabled(false);
        anguloVectorUnitario.setName("anguloVectorUnitario"); // NOI18N

        jSeparator1.setName("jSeparator1"); // NOI18N

        jLabel21.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel21.setText("NOTA: Coordenada geografica del punto de intersección de calles para ciudades con distribucion \"Manhattan Grid Layout\"  ");
        jLabel21.setName("jLabel21"); // NOI18N

        jLabel22.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel22.setText("o de la pared de intersección entre el eNodeB y el EU, para casos \"O-to-I\".");
        jLabel22.setName("jLabel22"); // NOI18N

        jLabel25.setText("[º]");
        jLabel25.setName("jLabel25"); // NOI18N

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel20.setText("[º]");
        jLabel20.setName("jLabel20"); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(gradosMinutosSegundos, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(decimal, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(latGrados, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(10, 10, 10)
                                .addComponent(longGrados)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(latMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(longMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(longSegundos)
                            .addComponent(latSegundos, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hemisferioLat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hemisferioLong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(longGradosDecimal)
                            .addComponent(latGradosDecimal, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(obtenerPunto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(limpiarCampos))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(anguloVectorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(decimal)
                            .addComponent(gradosMinutosSegundos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(latGradosDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(longGradosDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hemisferioLat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hemisferioLong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(latGrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(latMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(latSegundos))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(longGrados)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(longMinutos)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(longSegundos)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(obtenerPunto)
                    .addComponent(limpiarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anguloVectorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(151, Short.MAX_VALUE)))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Otras Caracteristicas de Simulación"));
        jPanel6.setName("jPanel6"); // NOI18N

        jLabel28.setText("Probabilidad de Shadowing");
        jLabel28.setName("jLabel28"); // NOI18N

        minimaProbabilidadShadowing.setModel(new javax.swing.SpinnerNumberModel(0.05d, 0.0d, 1.0d, 0.02d));
        minimaProbabilidadShadowing.setName("minimaProbabilidadShadowing"); // NOI18N

        jLabel29.setText("Aplicacion del Shadow Fading");
        jLabel29.setName("jLabel29"); // NOI18N

        rangoShadowing.setName("rangoShadowing"); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(minimaProbabilidadShadowing, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rangoShadowing, 0, 169, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minimaProbabilidadShadowing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rangoShadowing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Configuracion de parametros de pequeña escala"));
        jPanel7.setName("jPanel7"); // NOI18N

        jLabel32.setText("Cantidad de grupos de rayos:");
        jLabel32.setName("jLabel32"); // NOI18N

        cantidadGrupos.setModel(new javax.swing.SpinnerNumberModel(1, 1, 30, 1));
        cantidadGrupos.setName("cantidadGrupos"); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cantidadGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(352, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantidadGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(6, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
    
    CoordenadaGeografica coordenadaPuntoRompimiento = new CoordenadaGeografica(0, 0, elevacion);
            // Si se ingresaron coordenadas geograficas en formato decimal
            if(decimal.isSelected()){
                try {
                    coordenadaPuntoRompimiento = new CoordenadaGeografica(Double.parseDouble(latGradosDecimal.getText()), Double.parseDouble(longGradosDecimal.getText()), elevacion);
                }catch (Exception NFE) {
                    System.out.println("Insercion de caracteres no numericos o no hay caracteres");
                }
                // Si se ingresaron coordenadas geograficas en formato grados minutos y segundos
            }else if(gradosMinutosSegundos.isSelected()){
                try {
                    DecimalFormat formateador = new DecimalFormat("##.###");
                    Number segundosLatDouble = formateador.parse(latSegundos.getText());
                    Number segundosLongDouble = formateador.parse(longSegundos.getText());
                    coordenadaPuntoRompimiento = new CoordenadaGeografica(Integer.parseInt(latGrados.getText()), Integer.parseInt(latMinutos.getText()), 
                                    (float)segundosLatDouble.doubleValue(),hemisferioLat.getSelectedItem().toString().charAt(0),Integer.parseInt(longGrados.getText()), 
                                    Integer.parseInt(longMinutos.getText()), (float)segundosLongDouble.doubleValue(), hemisferioLong.getSelectedItem().toString().charAt(0), elevacion);
                }catch (ParseException ex) {
                    //Logger.getLogger(VentanaConfiguracionSimulacion.class.getName()).log(Level.SEVERE, null, ex);
                    System.out.println("Insercion de caracteres no numericos o no hay caracteres");
                }catch (Exception NFE) {
                    System.out.println("Insercion de caracteres no numericos o no hay caracteres");
                }
            }
            
            try{
              controlador.getControladorVentanas().crearNuevoPathModeloITU(
                       coordenadaPuntoRompimiento, Integer.parseInt(numeroPath.getText()), tipoEscenario.getSelectedItem().toString(), 
                       tipoPath.getSelectedItem().toString(), Double.parseDouble(alturaPromedioEdificios.getValue().toString()),
                       Double.parseDouble(anchuraPromedioCalles.getValue().toString()), distrubucionUrbanistica.getSelectedItem().toString(),
                       Double.parseDouble(temperaturaAmbiente.getValue().toString()), Double.parseDouble(anguloVectorUnitario.getValue().toString()),
                       Double.parseDouble(minimaProbabilidadShadowing.getValue().toString()), rangoShadowing.getSelectedItem().toString(), Integer.parseInt(cantidadGrupos.getValue().toString()));
            }catch(NullPointerException NPE){
               controlador.getControladorVentanas().crearNuevoPathModeloITU(
                       coordenadaPuntoRompimiento, Integer.parseInt(numeroPath.getText()), tipoEscenario.getSelectedItem().toString(), 
                       tipoPath.getSelectedItem().toString(), Double.parseDouble(alturaPromedioEdificios.getValue().toString()),
                       Double.parseDouble(anchuraPromedioCalles.getValue().toString()), "" ,
                       Double.parseDouble(temperaturaAmbiente.getValue().toString()), Double.parseDouble(anguloVectorUnitario.getValue().toString()),
                       Double.parseDouble(minimaProbabilidadShadowing.getValue().toString()), rangoShadowing.getSelectedItem().toString(), Integer.parseInt(cantidadGrupos.getValue().toString()));
            }

        this.dispose();
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void botonCanelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCanelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
}//GEN-LAST:event_botonCanelarActionPerformed

private void tipoEscenarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoEscenarioActionPerformed
    // TODO add your handling code here:
    anguloVectorUnitario.setEnabled(false);
    if(tipoEscenario.getSelectedItem().toString().equals("InH")){
        tipoPath.setModel(new DefaultComboBoxModel(PathModelo_ITU_R_M2135.TIPOS_PATH1));
        alturaPromedioEdificios.setEnabled(false); alturaPromedioEdificios.setValue(0);
        anchuraPromedioCalles.setEnabled(false); anchuraPromedioCalles.setValue(0);
        distrubucionUrbanistica.setModel(new DefaultComboBoxModel());distrubucionUrbanistica.setEnabled(false);
        establecerEnabledPuntoGeografico(false);
    }else if(tipoEscenario.getSelectedItem().toString().equals("UMi")){
        tipoPath.setModel(new DefaultComboBoxModel(PathModelo_ITU_R_M2135.TIPOS_PATH2));
    }else if(tipoEscenario.getSelectedItem().toString().equals("UMa")){
        tipoPath.setModel(new DefaultComboBoxModel(PathModelo_ITU_R_M2135.TIPOS_PATH1));
        distrubucionUrbanistica.setModel(new DefaultComboBoxModel());distrubucionUrbanistica.setEnabled(false);
        establecerEnabledPuntoGeografico(false);
    }else if(tipoEscenario.getSelectedItem().toString().equals("SMa")){
        tipoPath.setModel(new DefaultComboBoxModel(PathModelo_ITU_R_M2135.TIPOS_PATH1));
        distrubucionUrbanistica.setModel(new DefaultComboBoxModel());distrubucionUrbanistica.setEnabled(false);
        establecerEnabledPuntoGeografico(false);
    }else if(tipoEscenario.getSelectedItem().toString().equals("RMa")){
        tipoPath.setModel(new DefaultComboBoxModel(PathModelo_ITU_R_M2135.TIPOS_PATH1));
        distrubucionUrbanistica.setModel(new DefaultComboBoxModel());distrubucionUrbanistica.setEnabled(false);
        establecerEnabledPuntoGeografico(false);
    }
}//GEN-LAST:event_tipoEscenarioActionPerformed

private void tipoPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoPathActionPerformed
// TODO add your handling code here:
    anguloVectorUnitario.setEnabled(false);
    if(tipoEscenario.getSelectedItem().toString().equals("UMi")){
        if(tipoPath.getSelectedItem().toString().equals("NLOS")){
            distrubucionUrbanistica.setEnabled(true);
            distrubucionUrbanistica.setModel(new DefaultComboBoxModel(PathModelo_ITU_R_M2135.DISTRIBUCIONES_CIUDADES));
            establecerEnabledPuntoGeografico(true);
            anchuraPromedioCalles.setEnabled(true);anchuraPromedioCalles.setModel(new javax.swing.SpinnerNumberModel(5.0d, 5.0d, 50.0d, 0.5d));
            alturaPromedioEdificios.setEnabled(false); alturaPromedioEdificios.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 50.0d, 0.5d));
        }else if(tipoPath.getSelectedItem().toString().equals("O-to-I")){
            distrubucionUrbanistica.setEnabled(true);
            distrubucionUrbanistica.setModel(new DefaultComboBoxModel(PathModelo_ITU_R_M2135.DISTRIBUCIONES_CIUDADES));
            establecerEnabledPuntoGeografico(true);
            anguloVectorUnitario.setEnabled(true);
            anchuraPromedioCalles.setEnabled(false); anchuraPromedioCalles.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 50.0d, 0.5d));
            alturaPromedioEdificios.setEnabled(false); alturaPromedioEdificios.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 50.0d, 0.5d));
        }else if(tipoPath.getSelectedItem().toString().equals("LOS")){
            distrubucionUrbanistica.setEnabled(false);
            distrubucionUrbanistica.setModel(new DefaultComboBoxModel());
            establecerEnabledPuntoGeografico(false); 
            anchuraPromedioCalles.setEnabled(false); anchuraPromedioCalles.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 50.0d, 0.5d));
            alturaPromedioEdificios.setEnabled(false); alturaPromedioEdificios.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 50.0d, 0.5d));
        }
    }else if(tipoEscenario.getSelectedItem().toString().equals("UMa")){
        if(tipoPath.getSelectedItem().toString().equals("NLOS")){
            anchuraPromedioCalles.setEnabled(true);anchuraPromedioCalles.setModel(new javax.swing.SpinnerNumberModel(5.0d, 5.0d, 50.0d, 0.5d));
            alturaPromedioEdificios.setEnabled(true); alturaPromedioEdificios.setModel(new javax.swing.SpinnerNumberModel(5.0d, 5.0d, 50.0d, 0.5d));
        }else if(tipoPath.getSelectedItem().toString().equals("LOS")){
            anchuraPromedioCalles.setEnabled(false); anchuraPromedioCalles.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 50.0d, 0.5d));
            alturaPromedioEdificios.setEnabled(false); alturaPromedioEdificios.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 50.0d, 0.5d));
        }
    }else if(tipoEscenario.getSelectedItem().toString().equals("SMa")){
        if(tipoPath.getSelectedItem().toString().equals("NLOS")){
            anchuraPromedioCalles.setEnabled(true); anchuraPromedioCalles.setModel(new javax.swing.SpinnerNumberModel(5.0d, 5.0d, 50.0d, 0.5d));
            alturaPromedioEdificios.setEnabled(true); alturaPromedioEdificios.setModel(new javax.swing.SpinnerNumberModel(5.0d, 5.0d, 50.0d, 0.5d));
        }else if(tipoPath.getSelectedItem().toString().equals("LOS")){
            anchuraPromedioCalles.setEnabled(true); anchuraPromedioCalles.setModel(new javax.swing.SpinnerNumberModel(5.0d, 5.0d, 50.0d, 0.5d));
            alturaPromedioEdificios.setEnabled(true); alturaPromedioEdificios.setModel(new javax.swing.SpinnerNumberModel(5.0d, 5.0d, 50.0d, 0.5d));
        }
    }else if(tipoEscenario.getSelectedItem().toString().equals("RMa")){
        if(tipoPath.getSelectedItem().toString().equals("NLOS")){
            anchuraPromedioCalles.setEnabled(true); anchuraPromedioCalles.setModel(new javax.swing.SpinnerNumberModel(5.0d, 5.0d, 50.0d, 0.5d));
            alturaPromedioEdificios.setEnabled(true); alturaPromedioEdificios.setModel(new javax.swing.SpinnerNumberModel(5.0d, 5.0d, 50.0d, 0.5d));
        }else if(tipoPath.getSelectedItem().toString().equals("LOS")){
            anchuraPromedioCalles.setEnabled(true); anchuraPromedioCalles.setModel(new javax.swing.SpinnerNumberModel(5.0d, 5.0d, 50.0d, 0.5d));
            alturaPromedioEdificios.setEnabled(true); alturaPromedioEdificios.setModel(new javax.swing.SpinnerNumberModel(5.0d, 5.0d, 50.0d, 0.5d));
        }
    }
}//GEN-LAST:event_tipoPathActionPerformed

private void gradosMinutosSegundosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradosMinutosSegundosActionPerformed
        // TODO add your handling code here:
        latGrados.setEditable(true);
        longGrados.setEditable(true);
        latMinutos.setEditable(true);
        longMinutos.setEditable(true);
        latSegundos.setEditable(true);
        longSegundos.setEditable(true);
        hemisferioLong.setEnabled(true);
        hemisferioLat.setEnabled(true);
                
        latGradosDecimal.setEditable(false); latGradosDecimal.setText("");
        longGradosDecimal.setEditable(false); longGradosDecimal.setText("");
}//GEN-LAST:event_gradosMinutosSegundosActionPerformed

private void decimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decimalActionPerformed
        // TODO add your handling code here:
        
        latGrados.setEditable(false); latGrados.setText("");
        longGrados.setEditable(false); longGrados.setText("");
        latMinutos.setEditable(false); latMinutos.setText("");
        longMinutos.setEditable(false); longMinutos.setText("");
        latSegundos.setEditable(false); latSegundos.setText("");
        longSegundos.setEditable(false); longSegundos.setText("");
        hemisferioLong.setEnabled(false); 
        hemisferioLat.setEnabled(false); 
        
        latGradosDecimal.setEditable(true);
        longGradosDecimal.setEditable(true);
}//GEN-LAST:event_decimalActionPerformed

private void obtenerPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obtenerPuntoActionPerformed
        // TODO add your handling code here:
        
        latGradosDecimal.setText("" + controlador.getLibroDeProyectos().getMapa().getObtenerPunto().getLatitudDecimal());
        longGradosDecimal.setText("" + controlador.getLibroDeProyectos().getMapa().getObtenerPunto().getLongitudDecimal());   
        controlador.getLibroDeProyectos().getMapa().getObtenerPunto().convertirLat_A_GradMinSeg();
        controlador.getLibroDeProyectos().getMapa().getObtenerPunto().convertirLong_A_GradMinSeg();
        
        DecimalFormat df = new DecimalFormat("##.###"); 
        
        latGrados.setText("" + controlador.getLibroDeProyectos().getMapa().getObtenerPunto().getLatitudGrados());
        latMinutos.setText("" + controlador.getLibroDeProyectos().getMapa().getObtenerPunto().getLatitudMinutos());
        latSegundos.setText("" + df.format(controlador.getLibroDeProyectos().getMapa().getObtenerPunto().getLatitudSegundos()));    
        hemisferioLat.setSelectedItem("" + controlador.getLibroDeProyectos().getMapa().getObtenerPunto().getHemisferioLatitud());
        
        longGrados.setText("" + controlador.getLibroDeProyectos().getMapa().getObtenerPunto().getLongitudGrados());
        longMinutos.setText("" + controlador.getLibroDeProyectos().getMapa().getObtenerPunto().getLongitudMinutos());
        longSegundos.setText("" + df.format(controlador.getLibroDeProyectos().getMapa().getObtenerPunto().getLongitudSegundos()));
        
        hemisferioLong.setSelectedItem("" + controlador.getLibroDeProyectos().getMapa().getObtenerPunto().getHemisferioLongitud());
        elevacion = controlador.getLibroDeProyectos().getMapa().getObtenerPunto().getElevacion();
}//GEN-LAST:event_obtenerPuntoActionPerformed

private void limpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarCamposActionPerformed
        // TODO add your handling code here:
        latGrados.setText("");
        longGrados.setText("");
        latMinutos.setText("");
        longMinutos.setText("");
        latSegundos.setText("");
        longSegundos.setText("");
        latGradosDecimal.setText("");
        longGradosDecimal.setText("");
}//GEN-LAST:event_limpiarCamposActionPerformed

private void distrubucionUrbanisticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distrubucionUrbanisticaActionPerformed
// TODO add your handling code here:
    if(tipoPath.getSelectedItem().toString().equals("O-to-I")){
        if(distrubucionUrbanistica.getSelectedItem().toString().equals("Manhattan Grid Layout")
            ||distrubucionUrbanistica.getSelectedItem().toString().equals("Hexagonal Layout")){
                establecerEnabledPuntoGeografico(true);
        }else{
                establecerEnabledPuntoGeografico(false);
        }
    }else if(tipoPath.getSelectedItem().toString().equals("NLOS")){
        if(distrubucionUrbanistica.getSelectedItem().toString().equals("Manhattan Grid Layout")){
                establecerEnabledPuntoGeografico(true);
        }else{
                establecerEnabledPuntoGeografico(false);
        }
    }
    
    
    
    
    
    
}//GEN-LAST:event_distrubucionUrbanisticaActionPerformed

private void botonProbabilidadLOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonProbabilidadLOSActionPerformed
// TODO add your handling code here:
    
    controlador.getControladorVentanas().obtenerProbabilidadLOSOutdoorLinkPredeterminado(tipoEscenario.getSelectedItem().toString(), Double.parseDouble(distanciaEnlace.getText()));
    
}//GEN-LAST:event_botonProbabilidadLOSActionPerformed

private void establecerEnabledPuntoGeografico(boolean afirmacion){
    gradosMinutosSegundos.setEnabled(afirmacion);
    decimal.setEnabled(afirmacion);
    
    latGrados.setEnabled(afirmacion); 
    latMinutos.setEnabled(afirmacion);
    latSegundos.setEnabled(afirmacion);
    longGrados.setEnabled(afirmacion);
    longMinutos.setEnabled(afirmacion);
    longSegundos.setEnabled(afirmacion);
    hemisferioLat.setEnabled(afirmacion);
    hemisferioLong.setEnabled(afirmacion);
    latGradosDecimal.setEnabled(afirmacion);
    longGradosDecimal.setEnabled(afirmacion);
    obtenerPunto.setEnabled(afirmacion);
    limpiarCampos.setEnabled(afirmacion);
    
    latGrados.setText("0");
    latMinutos.setText("0");
    latSegundos.setText("0");
    longGrados.setText("0");
    longMinutos.setText("0");
    longSegundos.setText("0");
    latGradosDecimal.setText("0");
    longGradosDecimal.setText("0");
}


    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner alturaPromedioEdificios;
    private javax.swing.JSpinner anchuraPromedioCalles;
    private javax.swing.JSpinner anguloVectorUnitario;
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCanelar;
    private javax.swing.JButton botonProbabilidadLOS;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JSpinner cantidadGrupos;
    private javax.swing.JRadioButton decimal;
    private javax.swing.JTextField distanciaEnlace;
    private javax.swing.JComboBox distrubucionUrbanistica;
    private javax.swing.JRadioButton gradosMinutosSegundos;
    private javax.swing.JComboBox hemisferioLat;
    private javax.swing.JComboBox hemisferioLong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField latGrados;
    private javax.swing.JTextField latGradosDecimal;
    private javax.swing.JTextField latMinutos;
    private javax.swing.JTextField latSegundos;
    private javax.swing.JButton limpiarCampos;
    private javax.swing.JTextField longGrados;
    private javax.swing.JTextField longGradosDecimal;
    private javax.swing.JTextField longMinutos;
    private javax.swing.JTextField longSegundos;
    private javax.swing.JSpinner minimaProbabilidadShadowing;
    private javax.swing.JTextField numeroPath;
    private javax.swing.JButton obtenerPunto;
    private javax.swing.JComboBox rangoShadowing;
    private javax.swing.JSpinner temperaturaAmbiente;
    private javax.swing.JComboBox tipoEscenario;
    private javax.swing.JComboBox tipoPath;
    // End of variables declaration//GEN-END:variables
}
