/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FramePrincipal.java
 *
 * Created on 17/07/2010, 06:46:25 PM
 */

package Vista.general;

import Controlador.ControladorGeneral;
import Libreria.CentrarScreen;
import Vista.barras.BarraEstado;
import Vista.barras.BarraHerramientasPrincipal;
import Vista.barras.HerramientasPrincipales;
import Vista.general.PanelPrincipal;
import Vista.ventanas.Proyecto.VentanaEstablecerProyecto;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JSeparator;

/**
 *
 * @author Bejarano
 */
public class FramePrincipal extends javax.swing.JFrame {

    private GridBagLayout layout;
    //private Propiedades barraPropiedades;
    private BarraHerramientasPrincipal barraHerramientas;
    private PanelPrincipal principal;
    private BarraEstado barraEstado;

    private GridBagConstraints gbc;
    private ControladorGeneral controlador;

    /** Creates new form FramePrincipal */
    public FramePrincipal(ControladorGeneral controlador) {
        this.controlador = controlador;
        initComponents();
        
        //barraPropiedades = new Propiedades(controlador);
        //this.setJMenuBar(barraPropiedades);

        System.setProperty ("sun.awt.noerasebackground", "true");


        gbc = new GridBagConstraints();
        layout = new GridBagLayout();
        this.setLayout(layout);
        
        gbc.gridwidth = 1;
        gbc.gridheight = 1;
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 3.0;
        gbc.weighty = 0.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.anchor = GridBagConstraints.NORTH;
        
        barraHerramientas = new BarraHerramientasPrincipal(controlador);
        layout.setConstraints(barraHerramientas, gbc);
        add(barraHerramientas);

        gbc.gridwidth = 1;
        gbc.gridheight = 1;
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 0.0;
        gbc.weighty = 0.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.anchor = GridBagConstraints.NORTH;

        JSeparator separador = new JSeparator();
        layout.setConstraints(separador, gbc);
        add(separador);

        gbc.gridwidth = 1;
        gbc.gridheight = 1;
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 2.0;
        gbc.fill = GridBagConstraints.BOTH;
        
        principal = new PanelPrincipal(controlador);
        layout.setConstraints(principal, gbc);
        add(principal);

        gbc.gridwidth = 1;
        gbc.gridheight = 1;
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.weightx = 0.0;
        gbc.weighty = 0.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.anchor = GridBagConstraints.NORTH;

        JSeparator separador2 = new JSeparator();
        layout.setConstraints(separador2, gbc);
        add(separador2);

        gbc.gridwidth = 1;
        gbc.gridheight = 1;
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.weightx = 8.0;
        gbc.weighty = 0.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;

        barraEstado = new BarraEstado(controlador);
        layout.setConstraints(barraEstado, gbc);
        add(barraEstado);

        this.controlador.conectar(principal, barraPropiedades, barraHerramientas, barraEstado);
        
        Dimension dPantalla = Toolkit.getDefaultToolkit( ).getScreenSize( );
        this.setTitle("Mobile Network Designer ver 1.0.0");
        this.setSize(dPantalla.width, dPantalla.height-30);
        //this.setIconImage(new ImageIcon("data/PropertyBar/transmit.png").getImage());
        this.setIconImage(new ImageIcon("src/Images/otros/Icono PNG 32x32.png").getImage());
        this.setVisible(true);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        barraPropiedades = new javax.swing.JMenuBar();
        archivo = new javax.swing.JMenu();
        nuevoProyecto = new javax.swing.JMenuItem();
        eliminarProyecto = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        abrirProyecto = new javax.swing.JMenuItem();
        guardar = new javax.swing.JMenuItem();
        guardarComoBoton = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        salir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        ItemEstablecerProyecto = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        run = new javax.swing.JMenuItem();
        stop = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        configSimulacion = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        crearSitio = new javax.swing.JMenuItem();
        editarSitio = new javax.swing.JMenuItem();
        eliminarSitio = new javax.swing.JMenuItem();
        herramientasEquiposUsuario = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        crearRAN = new javax.swing.JMenuItem();
        editarRAN = new javax.swing.JMenuItem();
        eliminarRAN = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        crearNuevoENodeB = new javax.swing.JMenuItem();
        editarENodeB = new javax.swing.JMenuItem();
        EliminarENodeB = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        crearVentanaNuevoOutdoorLink = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        gestionAntenas = new javax.swing.JMenuItem();
        gestionEquipos = new javax.swing.JMenuItem();
        gestionAtenuadores = new javax.swing.JMenuItem();
        gestionConexionesIndoor = new javax.swing.JMenuItem();
        ayuda = new javax.swing.JMenu();
        about = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        archivo.setMnemonic('A');
        archivo.setText("Archivo");

        nuevoProyecto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        nuevoProyecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/package_add.png"))); // NOI18N
        nuevoProyecto.setText("Nuevo Proyecto");
        nuevoProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoProyectoActionPerformed(evt);
            }
        });
        archivo.add(nuevoProyecto);

        eliminarProyecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/package_delete.png"))); // NOI18N
        eliminarProyecto.setText("Eliminar proyecto");
        eliminarProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarProyectoActionPerformed(evt);
            }
        });
        archivo.add(eliminarProyecto);
        archivo.add(jSeparator2);

        abrirProyecto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        abrirProyecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/folder-project.png"))); // NOI18N
        abrirProyecto.setText("Abrir Proyecto");
        abrirProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirProyectoActionPerformed(evt);
            }
        });
        archivo.add(abrirProyecto);

        guardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/disk.png"))); // NOI18N
        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        archivo.add(guardar);

        guardarComoBoton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        guardarComoBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/save_as.png"))); // NOI18N
        guardarComoBoton.setText("Guardar como");
        guardarComoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarComoBotonActionPerformed(evt);
            }
        });
        archivo.add(guardarComoBoton);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/application-import.png"))); // NOI18N
        jMenu5.setText("Importar");
        jMenu5.setEnabled(false);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setText("Proyecto...");
        jMenu5.add(jMenuItem7);

        archivo.add(jMenu5);

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/book.png"))); // NOI18N
        jMenuItem10.setText("Propiedades del ProjectBook");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        archivo.add(jMenuItem10);
        archivo.add(jSeparator1);

        salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        archivo.add(salir);

        barraPropiedades.add(archivo);

        jMenu2.setMnemonic('E');
        jMenu2.setText("Edicion");
        barraPropiedades.add(jMenu2);

        jMenu1.setMnemonic('M');
        jMenu1.setText("Mapa");

        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/map.png"))); // NOI18N
        jMenuItem12.setText("Configuración Cartográfica");
        jMenu1.add(jMenuItem12);

        barraPropiedades.add(jMenu1);

        jMenu8.setText("Proyecto");

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/property-blue.png"))); // NOI18N
        jMenuItem8.setText("Propiedades del Proyecto");
        jMenu8.add(jMenuItem8);

        ItemEstablecerProyecto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        ItemEstablecerProyecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/package-share.png"))); // NOI18N
        ItemEstablecerProyecto.setText("Establecer Proyecto Predetermindo...");
        ItemEstablecerProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemEstablecerProyectoActionPerformed(evt);
            }
        });
        jMenu8.add(ItemEstablecerProyecto);

        barraPropiedades.add(jMenu8);

        jMenu13.setText("Simulación");

        run.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        run.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/control_play_blue.png"))); // NOI18N
        run.setText("Correr Simulacion");
        run.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runActionPerformed(evt);
            }
        });
        jMenu13.add(run);

        stop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/control_stop_blue.png"))); // NOI18N
        stop.setText("Parar Simulacion");
        stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopActionPerformed(evt);
            }
        });
        jMenu13.add(stop);
        jMenu13.add(jSeparator5);

        configSimulacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/analizer.png"))); // NOI18N
        configSimulacion.setText("Configuración de Simulación");
        configSimulacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configSimulacionActionPerformed(evt);
            }
        });
        jMenu13.add(configSimulacion);

        barraPropiedades.add(jMenu13);

        jMenu3.setMnemonic('V');
        jMenu3.setText("Vista");

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/application_tile_horizontal.png"))); // NOI18N
        jMenuItem4.setText("Vista Vertical");
        jMenu3.add(jMenuItem4);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/application_split.png"))); // NOI18N
        jMenuItem5.setText("Vista Horizontal");
        jMenu3.add(jMenuItem5);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/application_tile_normal.png"))); // NOI18N
        jMenuItem6.setText("Vista General");
        jMenu3.add(jMenuItem6);

        barraPropiedades.add(jMenu3);

        jMenu6.setMnemonic('H');
        jMenu6.setText("Herramientas");

        jMenu10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/building (1).png"))); // NOI18N
        jMenu10.setText("Herramientas de Sitio");

        crearSitio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        crearSitio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/building_add.png"))); // NOI18N
        crearSitio.setText("Crear Nuevo Sitio");
        crearSitio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearSitioActionPerformed(evt);
            }
        });
        jMenu10.add(crearSitio);

        editarSitio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/building_edit.png"))); // NOI18N
        editarSitio.setText("Editar Sitio Existente");
        editarSitio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarSitioActionPerformed(evt);
            }
        });
        jMenu10.add(editarSitio);

        eliminarSitio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/building_delete.png"))); // NOI18N
        eliminarSitio.setText("Eliminar Sitio Existente");
        eliminarSitio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarSitioActionPerformed(evt);
            }
        });
        jMenu10.add(eliminarSitio);

        jMenu6.add(jMenu10);

        herramientasEquiposUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/blackberry_white.png"))); // NOI18N
        herramientasEquiposUsuario.setText("Herramientas Equipos de Usuario");

        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/blackberry_white-add.png"))); // NOI18N
        jMenuItem11.setText("Crear Nuevo EU");
        herramientasEquiposUsuario.add(jMenuItem11);

        jMenu6.add(herramientasEquiposUsuario);

        jMenu11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/network-wireless.png"))); // NOI18N
        jMenu11.setText("Herramientas de Radio Access Networks");

        crearRAN.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        crearRAN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/RAN-16-add.png"))); // NOI18N
        crearRAN.setText("Crear Nueva RAN");
        crearRAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearRANActionPerformed(evt);
            }
        });
        jMenu11.add(crearRAN);

        editarRAN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/RAN-16-edit.png"))); // NOI18N
        editarRAN.setText("Editar RAN");
        editarRAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarRANActionPerformed(evt);
            }
        });
        jMenu11.add(editarRAN);

        eliminarRAN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/RAN-16-remove.png"))); // NOI18N
        eliminarRAN.setText("Eliminar RAN");
        eliminarRAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarRANActionPerformed(evt);
            }
        });
        jMenu11.add(eliminarRAN);
        jMenu11.add(jSeparator3);

        crearNuevoENodeB.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        crearNuevoENodeB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/eNB6-16-add.png"))); // NOI18N
        crearNuevoENodeB.setText("Crear Nuevo eNodeB");
        crearNuevoENodeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearNuevoENodeBActionPerformed(evt);
            }
        });
        jMenu11.add(crearNuevoENodeB);

        editarENodeB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/eNB6-16-edit.png"))); // NOI18N
        editarENodeB.setText("Editar eNodeB");
        editarENodeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarENodeBActionPerformed(evt);
            }
        });
        jMenu11.add(editarENodeB);

        EliminarENodeB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/eNB6-16-remove.png"))); // NOI18N
        EliminarENodeB.setText("Eliminar eNodeB");
        EliminarENodeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarENodeBActionPerformed(evt);
            }
        });
        jMenu11.add(EliminarENodeB);

        jMenu6.add(jMenu11);

        jMenu12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/connect.png"))); // NOI18N
        jMenu12.setText("Herramientas de Conexiones Outdoor");

        crearVentanaNuevoOutdoorLink.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        crearVentanaNuevoOutdoorLink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/connect-add.png"))); // NOI18N
        crearVentanaNuevoOutdoorLink.setText("Crear Nueva Conexión Outdoor");
        crearVentanaNuevoOutdoorLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearVentanaNuevoOutdoorLinkActionPerformed(evt);
            }
        });
        jMenu12.add(crearVentanaNuevoOutdoorLink);

        jMenu6.add(jMenu12);

        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/network-cloud.png"))); // NOI18N
        jMenu9.setText("Elementos de la EPC");

        jMenuItem15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/server.png"))); // NOI18N
        jMenuItem15.setText("Crear Nuevo Dispositivo MME");
        jMenuItem15.setEnabled(false);
        jMenu9.add(jMenuItem15);

        jMenuItem16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/S-GW-16.png"))); // NOI18N
        jMenuItem16.setText("Crear Nuevo Dispositivo S-GW");
        jMenuItem16.setEnabled(false);
        jMenu9.add(jMenuItem16);

        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/PDN-GW-16.png"))); // NOI18N
        jMenuItem14.setText("Crear Nuevo Dispositivo PDN-GW");
        jMenuItem14.setEnabled(false);
        jMenu9.add(jMenuItem14);

        jMenuItem17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/HSS-16.png"))); // NOI18N
        jMenuItem17.setText("Crear Nuevo Dispositivo HHS");
        jMenuItem17.setEnabled(false);
        jMenu9.add(jMenuItem17);

        jMenu6.add(jMenu9);
        jMenu6.add(jSeparator4);

        gestionAntenas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        gestionAntenas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/satellite_dish.png"))); // NOI18N
        gestionAntenas.setText("Gestion de Antenas");
        gestionAntenas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionAntenasActionPerformed(evt);
            }
        });
        jMenu6.add(gestionAntenas);

        gestionEquipos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        gestionEquipos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/stanchion.png"))); // NOI18N
        gestionEquipos.setText("Gestion de Equipos de Radio");
        gestionEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionEquiposActionPerformed(evt);
            }
        });
        jMenu6.add(gestionEquipos);

        gestionAtenuadores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        gestionAtenuadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/port.png"))); // NOI18N
        gestionAtenuadores.setText("Gestion de Elementos de Atenuación");
        gestionAtenuadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionAtenuadoresActionPerformed(evt);
            }
        });
        jMenu6.add(gestionAtenuadores);

        gestionConexionesIndoor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        gestionConexionesIndoor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/connect-out.png"))); // NOI18N
        gestionConexionesIndoor.setText("Gestion de Conexiones Indoor");
        gestionConexionesIndoor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionConexionesIndoorActionPerformed(evt);
            }
        });
        jMenu6.add(gestionConexionesIndoor);

        barraPropiedades.add(jMenu6);

        ayuda.setMnemonic('Y');
        ayuda.setText("Ayuda");
        ayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayudaActionPerformed(evt);
            }
        });

        about.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        about.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/Icono PNG 16x16.png"))); // NOI18N
        about.setText("Acerca de...");
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });
        ayuda.add(about);

        barraPropiedades.add(ayuda);

        setJMenuBar(barraPropiedades);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 574, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void nuevoProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoProyectoActionPerformed
        // TODO add your handling code here:
        controlador.getControladorBotones().crearVentanaNuevoProyecto();
    }//GEN-LAST:event_nuevoProyectoActionPerformed

    private void ItemEstablecerProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemEstablecerProyectoActionPerformed
        // TODO add your handling code here:
        controlador.getControladorBotones().crearVentanaEstablecerProyectoPredeterminado();
    }//GEN-LAST:event_ItemEstablecerProyectoActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        controlador.getControladorBotones().crearVentanaConfiguracionProjectBook();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void crearSitioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearSitioActionPerformed
        // TODO add your handling code here:
        controlador.getControladorBotones().nuevaVentanaNuevoSitio();
    }//GEN-LAST:event_crearSitioActionPerformed

    private void eliminarSitioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarSitioActionPerformed
        // TODO add your handling code here:
        controlador.getControladorBotones().crearVentanaEliminarSitio();
    }//GEN-LAST:event_eliminarSitioActionPerformed

    private void crearRANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearRANActionPerformed
        // TODO add your handling code here:
         controlador.getControladorBotones().crearVentanaNuevoRAN();
    }//GEN-LAST:event_crearRANActionPerformed

    private void eliminarRANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarRANActionPerformed
        // TODO add your handling code here:
        controlador.getControladorBotones().crearVentanaEliminarRAN();
    }//GEN-LAST:event_eliminarRANActionPerformed

    private void editarRANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarRANActionPerformed
        // TODO add your handling code here:
        controlador.getControladorBotones().crearVentanaEditarRAN();
    }//GEN-LAST:event_editarRANActionPerformed

    private void crearNuevoENodeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearNuevoENodeBActionPerformed
        // TODO add your handling code here:
        controlador.getControladorBotones().crearVentanaNuevoNodeB();
    }//GEN-LAST:event_crearNuevoENodeBActionPerformed

    private void editarENodeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarENodeBActionPerformed
        // TODO add your handling code here:
        controlador.getControladorBotones().crearVentanaEditarNodoB();
    }//GEN-LAST:event_editarENodeBActionPerformed

    private void EliminarENodeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarENodeBActionPerformed
        // TODO add your handling code here:
        controlador.getControladorBotones().crearVentanaEliminarNodoB();
    }//GEN-LAST:event_EliminarENodeBActionPerformed

private void gestionAntenasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionAntenasActionPerformed
// TODO add your handling code here:
    controlador.getControladorBotones().crearVenatanGestionDeAntenas();
}//GEN-LAST:event_gestionAntenasActionPerformed

private void editarSitioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarSitioActionPerformed
// TODO add your handling code here:
    controlador.getControladorBotones().crearVentanaEditarSitio();
}//GEN-LAST:event_editarSitioActionPerformed

private void gestionConexionesIndoorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionConexionesIndoorActionPerformed
// TODO add your handling code here:
    controlador.getControladorBotones().crearVenatanaGestionIndoorLink();
}//GEN-LAST:event_gestionConexionesIndoorActionPerformed

private void crearVentanaNuevoOutdoorLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearVentanaNuevoOutdoorLinkActionPerformed
// TODO add your handling code here:
    controlador.getControladorBotones().crearVentanaNuevoEnlaceOutdoor();
}//GEN-LAST:event_crearVentanaNuevoOutdoorLinkActionPerformed

private void runActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runActionPerformed
// TODO add your handling code here:
    controlador.getControladorHilos().crearVentanaCorrerSimulacion();
    stop.setEnabled(true);
    run.setEnabled(false);
}//GEN-LAST:event_runActionPerformed

private void stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopActionPerformed
// TODO add your handling code here:
    controlador.getControladorHilos().pararSimulacion();
    run.setEnabled(true);
    stop.setEnabled(false);
}//GEN-LAST:event_stopActionPerformed

private void configSimulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configSimulacionActionPerformed
// TODO add your handling code here:
    controlador.getControladorBotones().crearVentanaConfiguracionSimulacion();
}//GEN-LAST:event_configSimulacionActionPerformed

private void gestionEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionEquiposActionPerformed
// TODO add your handling code here
     controlador.getControladorBotones().crearVentanaGestionEquiposRadio();
}//GEN-LAST:event_gestionEquiposActionPerformed

private void gestionAtenuadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionAtenuadoresActionPerformed
// TODO add your handling code here:
     controlador.getControladorBotones().crearVenatanaGestionAtenuadores();
}//GEN-LAST:event_gestionAtenuadoresActionPerformed

private void ayudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayudaActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_ayudaActionPerformed

private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
// TODO add your handling code here:
    controlador.getControladorBotones().crearVentanaAbout();
}//GEN-LAST:event_aboutActionPerformed

private void guardarComoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarComoBotonActionPerformed
// TODO add your handling code here:
    controlador.getControladorBotones().guardarProyectoComo();
}//GEN-LAST:event_guardarComoBotonActionPerformed

private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
// TODO add your handling code here:
    controlador.getControladorBotones().guardarProyecto();
}//GEN-LAST:event_guardarActionPerformed

private void abrirProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirProyectoActionPerformed
// TODO add your handling code here:
    controlador.getControladorBotones().abrirProyecto();
}//GEN-LAST:event_abrirProyectoActionPerformed

private void eliminarProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarProyectoActionPerformed
// TODO add your handling code here:
    controlador.getControladorBotones().crearVentanaEliminarProyecto();
}//GEN-LAST:event_eliminarProyectoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem EliminarENodeB;
    private javax.swing.JMenuItem ItemEstablecerProyecto;
    private javax.swing.JMenuItem about;
    private javax.swing.JMenuItem abrirProyecto;
    private javax.swing.JMenu archivo;
    private javax.swing.JMenu ayuda;
    private javax.swing.JMenuBar barraPropiedades;
    private javax.swing.JMenuItem configSimulacion;
    private javax.swing.JMenuItem crearNuevoENodeB;
    private javax.swing.JMenuItem crearRAN;
    private javax.swing.JMenuItem crearSitio;
    private javax.swing.JMenuItem crearVentanaNuevoOutdoorLink;
    private javax.swing.JMenuItem editarENodeB;
    private javax.swing.JMenuItem editarRAN;
    private javax.swing.JMenuItem editarSitio;
    private javax.swing.JMenuItem eliminarProyecto;
    private javax.swing.JMenuItem eliminarRAN;
    private javax.swing.JMenuItem eliminarSitio;
    private javax.swing.JMenuItem gestionAntenas;
    private javax.swing.JMenuItem gestionAtenuadores;
    private javax.swing.JMenuItem gestionConexionesIndoor;
    private javax.swing.JMenuItem gestionEquipos;
    private javax.swing.JMenuItem guardar;
    private javax.swing.JMenuItem guardarComoBoton;
    private javax.swing.JMenu herramientasEquiposUsuario;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JMenuItem nuevoProyecto;
    private javax.swing.JMenuItem run;
    private javax.swing.JMenuItem salir;
    private javax.swing.JMenuItem stop;
    // End of variables declaration//GEN-END:variables

}
