/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelPrincipal.java
 *
 * Created on 21/07/2010, 12:51:39 PM
 */

package Vista.general;

import Controlador.ControladorGeneral;
import Vista.paneles.PanelArboles;
import Vista.paneles.PanelCaracteristicas;
import Vista.paneles.PanelConsolas;
import Vista.paneles.PanelDiagramas;
import Vista.paneles.PanelConexiones;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import javax.swing.JTextArea;

/**
 *
 * @author Bejarano
 */
public class PanelPrincipal extends javax.swing.JPanel {

    private JPanel panelIzquierdo;
    private JPanel panelDerechoArriba;
    private JPanel panelDerechoAbajo;

    private PanelDiagramas panelDiagramas;
    private PanelArboles panelArboles;
    private PanelConexiones panelConexiones;
    private PanelCaracteristicas panelCaracteristicas;
    private PanelConsolas panelConsolas;

    private ControladorGeneral controlador;

    /** Creates new form PanelPrincipal */
    public PanelPrincipal(ControladorGeneral controlador) {
        initComponents();
        this.controlador = controlador;

        
        panelDiagramas = new PanelDiagramas(controlador);
        panelArboles = new PanelArboles(controlador);
        panelConexiones = new PanelConexiones(controlador);
        panelCaracteristicas = new PanelCaracteristicas();
        panelConsolas = new PanelConsolas();
        
        div2.setTopComponent(panelDiagramas);
        divisor3.setLeftComponent(panelArboles);
        divisor3.setRightComponent(panelConexiones);
        divisor4.setLeftComponent(panelCaracteristicas);
        divisor4.setRightComponent(panelConsolas);
 
        
        //divisor1.setDividerLocation(0.2);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        divisor1 = new javax.swing.JSplitPane();
        divisor3 = new javax.swing.JSplitPane();
        div2 = new javax.swing.JSplitPane();
        divisor4 = new javax.swing.JSplitPane();

        divisor1.setBorder(null);
        divisor1.setDividerLocation(1000);
        divisor1.setResizeWeight(1.0);
        divisor1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        divisor1.setOneTouchExpandable(true);

        divisor3.setDividerLocation(450);
        divisor3.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        divisor3.setResizeWeight(0.5);
        divisor3.setLastDividerLocation(450);
        divisor3.setMaximumSize(new java.awt.Dimension(400, 2147483647));
        divisor3.setMinimumSize(new java.awt.Dimension(250, 53));
        divisor3.setOneTouchExpandable(true);
        divisor1.setRightComponent(divisor3);

        div2.setDividerLocation(700);
        div2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        div2.setResizeWeight(1.0);
        div2.setOneTouchExpandable(true);

        divisor4.setDividerLocation(480);
        divisor4.setResizeWeight(0.5);
        divisor4.setLastDividerLocation(20);
        divisor4.setMaximumSize(new java.awt.Dimension(2147483647, 200));
        divisor4.setMinimumSize(new java.awt.Dimension(100, 180));
        divisor4.setOneTouchExpandable(true);
        divisor4.setPreferredSize(new java.awt.Dimension(317, 25));
        div2.setBottomComponent(divisor4);

        divisor1.setLeftComponent(div2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(divisor1, javax.swing.GroupLayout.DEFAULT_SIZE, 1189, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(divisor1, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    public PanelDiagramas getPanelDiagramas(){
        return panelDiagramas;
    }

    public PanelArboles getPanelArboles(){
        return panelArboles;
    }

    public PanelCaracteristicas getPanelCaracteristicas(){
        return panelCaracteristicas;
    }

    public PanelConsolas getPanelConsolas(){
        return panelConsolas;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane div2;
    private javax.swing.JSplitPane divisor1;
    private javax.swing.JSplitPane divisor3;
    private javax.swing.JSplitPane divisor4;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the panelConexiones
     */
    public PanelConexiones getPanelConexiones() {
        return panelConexiones;
    }

}
