/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VentanaGestionInterfacesRadio.java
 *
 * Created on 14-oct-2011, 0:04:04
 */
package Vista.ventanas.RAN.Components.radios.interfacesRadio;

import Controlador.ControladorGeneral;
import Libreria.CentrarScreen;
import Modelo.PRO.Proyecto;
import Modelo.RAN.ENodeB;
import Modelo.RAN.TarjetaRadio;
import java.util.LinkedList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class VentanaGestionTarjetasRadio extends javax.swing.JDialog {

    private ControladorGeneral controlador;
    private String nombreRAN;
    private String eNodeB;
    
    /** Creates new form VentanaGestionInterfacesRadio */
    public VentanaGestionTarjetasRadio(java.awt.Frame parent, boolean modal, ControladorGeneral controlador, String nomRAN, String nomENodeB, String nomRadio) {
        super(parent, modal);
        this.controlador = controlador;
        initComponents();
        
        nombreRadio.setText(nomRadio);
        this.eNodeB = nomENodeB;
        this.nombreRAN = nomRAN;
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        nuevaTarjetaRadio = new javax.swing.JButton();
        eliminarTarjetaRadio = new javax.swing.JButton();
        editarTarjetaRadio = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        nuevaTarjetaInterconexion = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaTargetasInterconexion = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        nombreRadio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaTargetasRadio = new javax.swing.JTable();
        panelDiagramaEquipo = new javax.swing.JPanel();
        radioCard0 = new javax.swing.JLabel();
        radioCard1 = new javax.swing.JLabel();
        radioCard2 = new javax.swing.JLabel();
        radioCard3 = new javax.swing.JLabel();
        radioCard4 = new javax.swing.JLabel();
        radioCard5 = new javax.swing.JLabel();
        interconexionCard0 = new javax.swing.JLabel();
        interconexionCard1 = new javax.swing.JLabel();
        interconexionCard2 = new javax.swing.JLabel();
        interconexionCard3 = new javax.swing.JLabel();
        interconexionCard4 = new javax.swing.JLabel();
        interconexionCard5 = new javax.swing.JLabel();
        ChasisRadio = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        botonAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestion de Targetas de Equipo de Radio");
        setIconImage(new ImageIcon("src/Images/iconos16x16/network_adapter.png").getImage());
        setResizable(false);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setName("jPanel5"); // NOI18N

        jSeparator4.setName("jSeparator4"); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos32x32/network_adapter.png"))); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("Asistente para la Gestion de Tarjetas de Equipos de Radio");
        jLabel2.setName("jLabel2"); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(307, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)))
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setRollover(true);
        jToolBar1.setName("jToolBar1"); // NOI18N

        nuevaTarjetaRadio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos32x32/card-add.png"))); // NOI18N
        nuevaTarjetaRadio.setToolTipText("Nueva Tarjeta de Radio");
        nuevaTarjetaRadio.setFocusable(false);
        nuevaTarjetaRadio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nuevaTarjetaRadio.setName("nuevaTarjetaRadio"); // NOI18N
        nuevaTarjetaRadio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        nuevaTarjetaRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaTarjetaRadioActionPerformed(evt);
            }
        });
        jToolBar1.add(nuevaTarjetaRadio);

        eliminarTarjetaRadio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos32x32/card-remove.png"))); // NOI18N
        eliminarTarjetaRadio.setToolTipText("Eliminar Tarjeta de Radio");
        eliminarTarjetaRadio.setEnabled(false);
        eliminarTarjetaRadio.setFocusable(false);
        eliminarTarjetaRadio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        eliminarTarjetaRadio.setName("eliminarTarjetaRadio"); // NOI18N
        eliminarTarjetaRadio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        eliminarTarjetaRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarTarjetaRadioActionPerformed(evt);
            }
        });
        jToolBar1.add(eliminarTarjetaRadio);

        editarTarjetaRadio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos32x32/card-dit.png"))); // NOI18N
        editarTarjetaRadio.setToolTipText("Editar Tarjeta de Radio");
        editarTarjetaRadio.setEnabled(false);
        editarTarjetaRadio.setFocusable(false);
        editarTarjetaRadio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editarTarjetaRadio.setName("editarTarjetaRadio"); // NOI18N
        editarTarjetaRadio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        editarTarjetaRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarTarjetaRadioActionPerformed(evt);
            }
        });
        jToolBar1.add(editarTarjetaRadio);

        jSeparator1.setName("jSeparator1"); // NOI18N
        jToolBar1.add(jSeparator1);

        nuevaTarjetaInterconexion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos32x32/network_adapter-add.png"))); // NOI18N
        nuevaTarjetaInterconexion.setToolTipText("Crear Targeta de Interconexion...");
        nuevaTarjetaInterconexion.setEnabled(false);
        nuevaTarjetaInterconexion.setFocusable(false);
        nuevaTarjetaInterconexion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nuevaTarjetaInterconexion.setName("nuevaTarjetaInterconexion"); // NOI18N
        nuevaTarjetaInterconexion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(nuevaTarjetaInterconexion);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos32x32/network_adapter-remove.png"))); // NOI18N
        jButton2.setToolTipText("Eliminar Targeta de Interconexion...");
        jButton2.setEnabled(false);
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setName("jButton2"); // NOI18N
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos32x32/network_adapter-edit.png"))); // NOI18N
        jButton3.setToolTipText("Editar Targeta de Interconexion...");
        jButton3.setEnabled(false);
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setName("jButton3"); // NOI18N
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton3);

        jPanel2.add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 40));

        jSeparator2.setName("jSeparator2"); // NOI18N
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 720, 10));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Panel de Parametros de Tarjetas de Interconexion"));
        jPanel3.setName("jPanel3"); // NOI18N

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        tablaTargetasInterconexion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Slot", "Tipo Targeta", "Potencia Maxima", "Sensibilidad", "Modulacion", "Tecnologia Multiplexacion", "Duplex-Mode", "Banda de Frecuecia"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaTargetasInterconexion.setToolTipText("Tabla Antenas");
        tablaTargetasInterconexion.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tablaTargetasInterconexion.setEnabled(false);
        tablaTargetasInterconexion.setGridColor(new java.awt.Color(204, 204, 204));
        tablaTargetasInterconexion.setName("tablaTargetasInterconexion"); // NOI18N
        tablaTargetasInterconexion.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tablaTargetasInterconexion);
        tablaTargetasInterconexion.getColumnModel().getColumn(0).setPreferredWidth(30);
        tablaTargetasInterconexion.getColumnModel().getColumn(1).setPreferredWidth(130);
        tablaTargetasInterconexion.getColumnModel().getColumn(2).setPreferredWidth(100);
        tablaTargetasInterconexion.getColumnModel().getColumn(3).setPreferredWidth(80);
        tablaTargetasInterconexion.getColumnModel().getColumn(4).setPreferredWidth(80);
        tablaTargetasInterconexion.getColumnModel().getColumn(5).setPreferredWidth(140);
        tablaTargetasInterconexion.getColumnModel().getColumn(6).setPreferredWidth(80);
        tablaTargetasInterconexion.getColumnModel().getColumn(7).setPreferredWidth(120);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 147, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 420, 170));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setName("jPanel1"); // NOI18N

        nombreRadio.setEditable(false);
        nombreRadio.setName("nombreRadio"); // NOI18N

        jLabel5.setText("Equipo de Radio:");
        jLabel5.setName("jLabel5"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nombreRadio, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap())
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 420, 50));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Panel de Parametros de Tarjetas de Radio"));
        jPanel6.setName("jPanel6"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        tablaTargetasRadio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Slot", "Tipo Targeta", "Potencia Maxima", "Sensibilidad", "Modulacion", "Tecnologia Multiplexacion", "Duplex-Mode", "Banda de Frecuecia"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaTargetasRadio.setToolTipText("Tabla Antenas");
        tablaTargetasRadio.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tablaTargetasRadio.setGridColor(new java.awt.Color(204, 204, 204));
        tablaTargetasRadio.setName("tablaTargetasRadio"); // NOI18N
        tablaTargetasRadio.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tablaTargetasRadio);
        tablaTargetasRadio.getColumnModel().getColumn(0).setPreferredWidth(30);
        tablaTargetasRadio.getColumnModel().getColumn(1).setPreferredWidth(130);
        tablaTargetasRadio.getColumnModel().getColumn(2).setPreferredWidth(100);
        tablaTargetasRadio.getColumnModel().getColumn(3).setPreferredWidth(80);
        tablaTargetasRadio.getColumnModel().getColumn(4).setPreferredWidth(80);
        tablaTargetasRadio.getColumnModel().getColumn(5).setPreferredWidth(140);
        tablaTargetasRadio.getColumnModel().getColumn(6).setPreferredWidth(80);
        tablaTargetasRadio.getColumnModel().getColumn(7).setPreferredWidth(120);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 420, 170));

        panelDiagramaEquipo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        panelDiagramaEquipo.setName("panelDiagramaEquipo"); // NOI18N
        panelDiagramaEquipo.setLayout(null);

        radioCard0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Imagenes Grandes/TARGETA DE RADIO VACIO.png"))); // NOI18N
        radioCard0.setName("radioCard0"); // NOI18N
        panelDiagramaEquipo.add(radioCard0);
        radioCard0.setBounds(15, 25, 32, 164);

        radioCard1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Imagenes Grandes/TARGETA DE RADIO VACIO.png"))); // NOI18N
        radioCard1.setName("radioCard1"); // NOI18N
        panelDiagramaEquipo.add(radioCard1);
        radioCard1.setBounds(45, 25, 32, 164);

        radioCard2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Imagenes Grandes/TARGETA DE RADIO VACIO.png"))); // NOI18N
        radioCard2.setName("radioCard2"); // NOI18N
        panelDiagramaEquipo.add(radioCard2);
        radioCard2.setBounds(75, 25, 32, 164);

        radioCard3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Imagenes Grandes/TARGETA DE RADIO VACIO.png"))); // NOI18N
        radioCard3.setName("radioCard3"); // NOI18N
        panelDiagramaEquipo.add(radioCard3);
        radioCard3.setBounds(105, 25, 32, 164);

        radioCard4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Imagenes Grandes/TARGETA DE RADIO VACIO.png"))); // NOI18N
        radioCard4.setName("radioCard4"); // NOI18N
        panelDiagramaEquipo.add(radioCard4);
        radioCard4.setBounds(135, 25, 32, 164);

        radioCard5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Imagenes Grandes/TARGETA DE RADIO VACIO.png"))); // NOI18N
        radioCard5.setName("radioCard5"); // NOI18N
        panelDiagramaEquipo.add(radioCard5);
        radioCard5.setBounds(165, 25, 32, 164);

        interconexionCard0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Imagenes Grandes/TARGETAS DE INTERCONEXION - slot Empty.png"))); // NOI18N
        interconexionCard0.setName("interconexionCard0"); // NOI18N
        panelDiagramaEquipo.add(interconexionCard0);
        interconexionCard0.setBounds(10, 195, 190, 22);

        interconexionCard1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Imagenes Grandes/TARGETAS DE INTERCONEXION - slot Empty.png"))); // NOI18N
        interconexionCard1.setName("interconexionCard1"); // NOI18N
        panelDiagramaEquipo.add(interconexionCard1);
        interconexionCard1.setBounds(10, 215, 190, 22);

        interconexionCard2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Imagenes Grandes/TARGETAS DE INTERCONEXION - slot Empty.png"))); // NOI18N
        interconexionCard2.setName("interconexionCard2"); // NOI18N
        panelDiagramaEquipo.add(interconexionCard2);
        interconexionCard2.setBounds(10, 235, 190, 22);

        interconexionCard3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Imagenes Grandes/TARGETAS DE INTERCONEXION - slot Empty.png"))); // NOI18N
        interconexionCard3.setName("interconexionCard3"); // NOI18N
        panelDiagramaEquipo.add(interconexionCard3);
        interconexionCard3.setBounds(10, 255, 190, 22);

        interconexionCard4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Imagenes Grandes/TARGETAS DE INTERCONEXION - slot Empty.png"))); // NOI18N
        interconexionCard4.setName("interconexionCard4"); // NOI18N
        panelDiagramaEquipo.add(interconexionCard4);
        interconexionCard4.setBounds(10, 275, 190, 22);

        interconexionCard5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Imagenes Grandes/TARGETAS DE INTERCONEXION - slot Empty.png"))); // NOI18N
        interconexionCard5.setName("interconexionCard5"); // NOI18N
        panelDiagramaEquipo.add(interconexionCard5);
        interconexionCard5.setBounds(10, 295, 190, 22);

        ChasisRadio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Imagenes Grandes/RADIO GENERICO.png"))); // NOI18N
        ChasisRadio.setName("ChasisRadio"); // NOI18N
        panelDiagramaEquipo.add(ChasisRadio);
        ChasisRadio.setBounds(0, 0, 210, 404);

        jPanel2.add(panelDiagramaEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 210, 405));

        jTabbedPane1.addTab("Panel de Gestion de Tarjetas de Equipos de Radio", jPanel2);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.setName("jPanel4"); // NOI18N

        botonAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/tick.png"))); // NOI18N
        botonAceptar.setText("Cerrar");
        botonAceptar.setName("botonAceptar"); // NOI18N
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(577, Short.MAX_VALUE)
                .addComponent(botonAceptar))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        // TODO add your handling code here:
        //controlador.getControladorVentanas().editarENodeB(listaeNodeB.getSelectedItem().toString(), nombreENodeB.getText(), listaSitios.getSelectedItem().toString(), actualNombreRAN, listaRANs.getSelectedItem().toString(), Double.parseDouble(alturaTorre.getValue().toString()), tiposTorre.getSelectedItem().toString());
        this.dispose();
}//GEN-LAST:event_botonAceptarActionPerformed

private void nuevaTarjetaRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaTarjetaRadioActionPerformed
// TODO add your handling code here:
        VentanaNuevaTarjetaRadio ventana = new VentanaNuevaTarjetaRadio(new JFrame(), true, controlador, nombreRAN, eNodeB, nombreRadio.getText());
        CentrarScreen.centrarVentana(ventana);
        ventana.setVisible(true);
}//GEN-LAST:event_nuevaTarjetaRadioActionPerformed

private void eliminarTarjetaRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarTarjetaRadioActionPerformed
// TODO add your handling code here:
        try{
            VentanaEliminarTarjetaRadio ventana = new VentanaEliminarTarjetaRadio(new JFrame(), true, controlador, nombreRAN, eNodeB, nombreRadio.getText(), getFilaSeleccionadaTablaTargetasRadio());
            CentrarScreen.centrarVentana(ventana);
            ventana.setVisible(true);
        }catch(ArrayIndexOutOfBoundsException AIO){
            JOptionPane.showMessageDialog(null, "'No ha seleccionado ninguna targeta para eliminar'","Error 007: NullPointerException",JOptionPane.ERROR_MESSAGE);
        }
    
}//GEN-LAST:event_eliminarTarjetaRadioActionPerformed

private void editarTarjetaRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarTarjetaRadioActionPerformed
// TODO add your handling code here:
        try{
            VentanaEditarTarjetaRadio ventana = new VentanaEditarTarjetaRadio(new JFrame(), true, controlador, nombreRAN, eNodeB, nombreRadio.getText(), getFilaSeleccionadaTablaTargetasRadio());
            CentrarScreen.centrarVentana(ventana);
            ventana.setVisible(true);
        }catch(ArrayIndexOutOfBoundsException AIO){
            JOptionPane.showMessageDialog(null, "'No ha seleccionado ninguna targeta para editar'","Error 007: NullPointerException",JOptionPane.ERROR_MESSAGE);
        }
}//GEN-LAST:event_editarTarjetaRadioActionPerformed

public void actualizarTablaTarjetasRadio(TarjetaRadio[] tarjetas) {
        
        Object[][] parametros = new Object[tarjetas.length][8];
        String[] columnas = new String [] {
                "Slot", "Tipo Targeta", "Potencia Maxima", "Sensibilidad", "Modulacion", "Tecnologia Multiplexacion", "Duplex-Mode", "Banda de Frecuecia"
            };
        
        for(int j = 0; j < tarjetas.length; j++){
            System.out.println("Prueba Tabla Targetas: " + j);
            parametros[j][0] =  "" + tarjetas[j].getNumeroSlot();                
            parametros[j][1] = (Object)tarjetas[j].getTipoTargeta();
            parametros[j][2] = (Object)tarjetas[j].getPotenciaMaximaTX();
            parametros[j][3] = (Object)tarjetas[j].getSensibilidad();
            parametros[j][4] = (Object)tarjetas[j].getModulacion();
            parametros[j][5] = (Object)tarjetas[j].getTecnologiaMultiplexacion();
            parametros[j][6] = (Object)tarjetas[j].getDuplexMode();
            parametros[j][7] = (Object)tarjetas[j].getBandaFrecuencia();
        }
        DefaultTableModel modelo = new DefaultTableModel(parametros, columnas);
        tablaTargetasRadio.setModel(modelo);
        
        tablaTargetasRadio.getColumnModel().getColumn(0).setPreferredWidth(30);
        tablaTargetasRadio.getColumnModel().getColumn(1).setPreferredWidth(130);
        tablaTargetasRadio.getColumnModel().getColumn(2).setPreferredWidth(100);
        tablaTargetasRadio.getColumnModel().getColumn(3).setPreferredWidth(80);
        tablaTargetasRadio.getColumnModel().getColumn(4).setPreferredWidth(80);
        tablaTargetasRadio.getColumnModel().getColumn(5).setPreferredWidth(140);
        tablaTargetasRadio.getColumnModel().getColumn(6).setPreferredWidth(80);
        tablaTargetasRadio.getColumnModel().getColumn(7).setPreferredWidth(120);
        tablaTargetasRadio.setEnabled(true);
        
        if(tarjetas.length <= 0){
            eliminarTarjetaRadio.setEnabled(false);
            editarTarjetaRadio.setEnabled(false);
        }else{
             eliminarTarjetaRadio.setEnabled(true);
             editarTarjetaRadio.setEnabled(true);
         }
    }
    

    public void actualizarPanelTargetas(TarjetaRadio[] obtenerTargetasRadioSlotOcupados, String[] obtenerTargetasRadioSlotVacios) {
        // actualizacion slots vacios
        for(int j = 0; j < obtenerTargetasRadioSlotVacios.length; j++){
            switch((int)Integer.parseInt(obtenerTargetasRadioSlotVacios[j])){
                    case 0: radioCard0.setIcon(new ImageIcon("src/Images/Imagenes Grandes/TARGETA DE RADIO VACIO.png"));break;
                    case 1: radioCard1.setIcon(new ImageIcon("src/Images/Imagenes Grandes/TARGETA DE RADIO VACIO.png"));break;
                    case 2: radioCard2.setIcon(new ImageIcon("src/Images/Imagenes Grandes/TARGETA DE RADIO VACIO.png"));break;
                    case 3: radioCard3.setIcon(new ImageIcon("src/Images/Imagenes Grandes/TARGETA DE RADIO VACIO.png"));break;
                    case 4: radioCard4.setIcon(new ImageIcon("src/Images/Imagenes Grandes/TARGETA DE RADIO VACIO.png"));break;
                    case 5: radioCard5.setIcon(new ImageIcon("src/Images/Imagenes Grandes/TARGETA DE RADIO VACIO.png"));break;
                }
        }
        
        // acualizacion slots ocupados
        for(int i = 0; i < obtenerTargetasRadioSlotOcupados.length; i++){
            
            if(obtenerTargetasRadioSlotOcupados[i].getTipoTargeta().equals("LTE ADVENCED - TIPO-N")){
                switch(obtenerTargetasRadioSlotOcupados[i].getNumeroSlot()){
                    case 0: radioCard0.setIcon(new ImageIcon("src/Images/Imagenes Grandes/TARGETAS DE RADIO TIPO N LTE.png"));break;
                    case 1: radioCard1.setIcon(new ImageIcon("src/Images/Imagenes Grandes/TARGETAS DE RADIO TIPO N LTE.png"));break;
                    case 2: radioCard2.setIcon(new ImageIcon("src/Images/Imagenes Grandes/TARGETAS DE RADIO TIPO N LTE.png"));break;
                    case 3: radioCard3.setIcon(new ImageIcon("src/Images/Imagenes Grandes/TARGETAS DE RADIO TIPO N LTE.png"));break;
                    case 4: radioCard4.setIcon(new ImageIcon("src/Images/Imagenes Grandes/TARGETAS DE RADIO TIPO N LTE.png"));break;
                    case 5: radioCard5.setIcon(new ImageIcon("src/Images/Imagenes Grandes/TARGETAS DE RADIO TIPO N LTE.png"));break;
                }
            }else if(obtenerTargetasRadioSlotOcupados[i].getTipoTargeta().equals("LTE ADVENCED - SMA")){
                    switch(obtenerTargetasRadioSlotOcupados[i].getNumeroSlot()){
                    case 0: radioCard0.setIcon(new ImageIcon("src/Images/Imagenes Grandes/TARGETAS DE RADIO LTE SMA.png"));break;
                    case 1: radioCard1.setIcon(new ImageIcon("src/Images/Imagenes Grandes/TARGETAS DE RADIO LTE SMA.png"));break;
                    case 2: radioCard2.setIcon(new ImageIcon("src/Images/Imagenes Grandes/TARGETAS DE RADIO LTE SMA.png"));break;
                    case 3: radioCard3.setIcon(new ImageIcon("src/Images/Imagenes Grandes/TARGETAS DE RADIO LTE SMA.png"));break;
                    case 4: radioCard4.setIcon(new ImageIcon("src/Images/Imagenes Grandes/TARGETAS DE RADIO LTE SMA.png"));break;
                    case 5: radioCard5.setIcon(new ImageIcon("src/Images/Imagenes Grandes/TARGETAS DE RADIO LTE SMA.png"));break;
                }
             }
        }
    }

    public String getFilaSeleccionadaTablaTargetasRadio(){
          return (String) tablaTargetasRadio.getValueAt(tablaTargetasRadio.getSelectedRow(), 0).toString();
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ChasisRadio;
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton editarTarjetaRadio;
    private javax.swing.JButton eliminarTarjetaRadio;
    private javax.swing.JLabel interconexionCard0;
    private javax.swing.JLabel interconexionCard1;
    private javax.swing.JLabel interconexionCard2;
    private javax.swing.JLabel interconexionCard3;
    private javax.swing.JLabel interconexionCard4;
    private javax.swing.JLabel interconexionCard5;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField nombreRadio;
    private javax.swing.JButton nuevaTarjetaInterconexion;
    private javax.swing.JButton nuevaTarjetaRadio;
    private javax.swing.JPanel panelDiagramaEquipo;
    private javax.swing.JLabel radioCard0;
    private javax.swing.JLabel radioCard1;
    private javax.swing.JLabel radioCard2;
    private javax.swing.JLabel radioCard3;
    private javax.swing.JLabel radioCard4;
    private javax.swing.JLabel radioCard5;
    private javax.swing.JTable tablaTargetasInterconexion;
    private javax.swing.JTable tablaTargetasRadio;
    // End of variables declaration//GEN-END:variables

}
