/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VentanaEditarSitio.java
 *
 * Created on 21/08/2011, 04:55:53 PM
 */
package Vista.ventanas.Sitio;

import Controlador.ControladorGeneral;
import Modelo.PRO.Proyecto;
import Modelo.PRO.Sitio;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.util.LinkedList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class VentanaEditarSitio extends javax.swing.JDialog {

    private ControladorGeneral controlador;
    private String [] arraySitios;
    
    /** Creates new form VentanaEditarSitio */
    public VentanaEditarSitio(java.awt.Frame parent, boolean modal, ControladorGeneral controlador) {
        super(parent, modal);
        this.controlador = controlador;
        initComponents();
        
        String proyectoPredeterminado = controlador.getLibroDeProyectos().getProyectoPredeterminado();
        LinkedList <Proyecto> proyectos = controlador.getLibroDeProyectos().getProyectos();
        
        buttonGroup.add(gradosMinutosSegundos);
        buttonGroup.add(decimal);
        
        for(int i = 0; i < proyectos.size(); i++){
            
            if(proyectos.get(i).getNombre().equals(proyectoPredeterminado)){
                arraySitios = new String [proyectos.get(i).getGrupoSitios().size()];
                for(int j = 0; j < proyectos.get(i).getGrupoSitios().size(); j++){
                    arraySitios[j] = proyectos.get(i).getGrupoSitios().get(j).getNombreSitio();
                }
            }
        }
        
        try{
            sitios.setModel(new DefaultComboBoxModel(arraySitios));
            tipoSitio.setModel(new DefaultComboBoxModel(Sitio.tiposSitios));
        }catch(NullPointerException npe){
            JOptionPane.showMessageDialog(null, "'No exite ningun proyecto predeterminado'","Error 001: NullPointerException",JOptionPane.ERROR_MESSAGE);
        }
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        latGrados = new javax.swing.JTextField();
        longGrados = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        latMinutos = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        longMinutos = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        longSegundos = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        latSegundos = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        hemisferioLat = new javax.swing.JComboBox();
        gradosMinutosSegundos = new javax.swing.JRadioButton();
        decimal = new javax.swing.JRadioButton();
        latGradosDecimal = new javax.swing.JTextField();
        longGradosDecimal = new javax.swing.JTextField();
        obtenerPunto = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        limpiarCampos = new javax.swing.JButton();
        hemisferioLong = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        botonAceptar = new javax.swing.JButton();
        botonCanelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        nombreSitio = new javax.swing.JTextField();
        direccionSitio = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        pais = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        ciudad = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tipoSitio = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        sitios = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        encontrarSitio = new javax.swing.JButton();
        editarButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar Sitio");
        setIconImage(new ImageIcon("src/Images/iconos16x16/building_edit.png").getImage());
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setName("jPanel3"); // NOI18N

        jSeparator2.setName("jSeparator2"); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos32x32/building_edit.png"))); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("Asistente para la edicion de un sitio existente");
        jLabel2.setName("jLabel2"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(240, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ubicacion Geografica"));
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel3.setText("Latitud:");
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText("Longitud:");
        jLabel4.setName("jLabel4"); // NOI18N

        latGrados.setEditable(false);
        latGrados.setName("latGrados"); // NOI18N

        longGrados.setEditable(false);
        longGrados.setName("longGrados"); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel6.setText("º");
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel7.setText("º");
        jLabel7.setName("jLabel7"); // NOI18N

        latMinutos.setEditable(false);
        latMinutos.setName("latMinutos"); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel8.setText("'");
        jLabel8.setName("jLabel8"); // NOI18N

        longMinutos.setEditable(false);
        longMinutos.setName("longMinutos"); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel9.setText("'");
        jLabel9.setName("jLabel9"); // NOI18N

        longSegundos.setEditable(false);
        longSegundos.setName("longSegundos"); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("''");
        jLabel10.setName("jLabel10"); // NOI18N

        latSegundos.setEditable(false);
        latSegundos.setName("latSegundos"); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("''");
        jLabel11.setName("jLabel11"); // NOI18N

        hemisferioLat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N", "S" }));
        hemisferioLat.setEnabled(false);
        hemisferioLat.setName("hemisferioLat"); // NOI18N

        gradosMinutosSegundos.setSelected(true);
        gradosMinutosSegundos.setText("Grados, Minutos y Segundos");
        gradosMinutosSegundos.setEnabled(false);
        gradosMinutosSegundos.setName("gradosMinutosSegundos"); // NOI18N
        gradosMinutosSegundos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradosMinutosSegundosActionPerformed(evt);
            }
        });

        decimal.setText("Decimal");
        decimal.setEnabled(false);
        decimal.setName("decimal"); // NOI18N
        decimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decimalActionPerformed(evt);
            }
        });

        latGradosDecimal.setEditable(false);
        latGradosDecimal.setName("latGradosDecimal"); // NOI18N

        longGradosDecimal.setEditable(false);
        longGradosDecimal.setName("longGradosDecimal"); // NOI18N

        obtenerPunto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/arrow-curve-270-left.png"))); // NOI18N
        obtenerPunto.setText("Obtener Punto");
        obtenerPunto.setEnabled(false);
        obtenerPunto.setName("obtenerPunto"); // NOI18N
        obtenerPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obtenerPuntoActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel15.setText("º");
        jLabel15.setName("jLabel15"); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel16.setText("º");
        jLabel16.setName("jLabel16"); // NOI18N

        limpiarCampos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/eraser.png"))); // NOI18N
        limpiarCampos.setText(" Limpiar");
        limpiarCampos.setEnabled(false);
        limpiarCampos.setName("limpiarCampos"); // NOI18N
        limpiarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarCamposActionPerformed(evt);
            }
        });

        hemisferioLong.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "O", "E" }));
        hemisferioLong.setEnabled(false);
        hemisferioLong.setName("hemisferioLong"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(gradosMinutosSegundos, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(decimal, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(latGrados, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(10, 10, 10)
                                .addComponent(longGrados)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(latMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(longMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(longSegundos)
                            .addComponent(latSegundos, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hemisferioLat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hemisferioLong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(latGradosDecimal)
                            .addComponent(longGradosDecimal, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(obtenerPunto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(limpiarCampos)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(502, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gradosMinutosSegundos)
                    .addComponent(decimal))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(latGrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(latMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(latSegundos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(longGrados)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(longMinutos)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(longSegundos)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)))
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hemisferioLat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(latGradosDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(hemisferioLong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(longGradosDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(obtenerPunto)
                    .addComponent(limpiarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(68, 68, 68)
                    .addComponent(jLabel16)
                    .addContainerGap(58, Short.MAX_VALUE)))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.setName("jPanel4"); // NOI18N

        botonAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/tick.png"))); // NOI18N
        botonAceptar.setText(" Aceptar");
        botonAceptar.setName("botonAceptar"); // NOI18N
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        botonCanelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/cross-script.png"))); // NOI18N
        botonCanelar.setText(" Cancelar");
        botonCanelar.setName("botonCanelar"); // NOI18N
        botonCanelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCanelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(295, Short.MAX_VALUE)
                .addComponent(botonCanelar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(botonCanelar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacion General"));
        jPanel2.setName("jPanel2"); // NOI18N

        jLabel5.setText("* Nombre del Sitio:");
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel12.setText("Direccion del Sitio:");
        jLabel12.setName("jLabel12"); // NOI18N

        nombreSitio.setEditable(false);
        nombreSitio.setName("nombreSitio"); // NOI18N

        direccionSitio.setEditable(false);
        direccionSitio.setName("direccionSitio"); // NOI18N

        jLabel13.setText("* Pais:");
        jLabel13.setName("jLabel13"); // NOI18N

        pais.setEditable(false);
        pais.setName("pais"); // NOI18N

        jLabel14.setText("Ciudad:");
        jLabel14.setName("jLabel14"); // NOI18N

        ciudad.setEditable(false);
        ciudad.setName("ciudad"); // NOI18N

        jLabel18.setText("Tipo:");
        jLabel18.setName("jLabel18"); // NOI18N

        tipoSitio.setEnabled(false);
        tipoSitio.setName("tipoSitio"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreSitio, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pais, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(direccionSitio, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tipoSitio, 0, 180, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreSitio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(direccionSitio)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoSitio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                    .addComponent(pais)
                    .addComponent(ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Panel de Seleccion"));
        jPanel5.setName("jPanel5"); // NOI18N

        sitios.setName("sitios"); // NOI18N

        jLabel17.setText("Sitio a Editar:");
        jLabel17.setName("jLabel17"); // NOI18N

        encontrarSitio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/find.png"))); // NOI18N
        encontrarSitio.setText(" Encontrar");
        encontrarSitio.setName("encontrarSitio"); // NOI18N
        encontrarSitio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encontrarSitioActionPerformed(evt);
            }
        });

        editarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/pencil.png"))); // NOI18N
        editarButton.setText(" Editar");
        editarButton.setName("editarButton"); // NOI18N
        editarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(editarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(encontrarSitio))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sitios, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sitios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editarButton)
                    .addComponent(encontrarSitio)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gradosMinutosSegundosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradosMinutosSegundosActionPerformed
        // TODO add your handling code here:
        latGrados.setEditable(true);
        longGrados.setEditable(true);
        latMinutos.setEditable(true);
        longMinutos.setEditable(true);
        latSegundos.setEditable(true);
        longSegundos.setEditable(true);
        hemisferioLong.setEnabled(true);
        hemisferioLat.setEnabled(true);
        
        latGradosDecimal.setEditable(false); latGradosDecimal.setText("");
        longGradosDecimal.setEditable(false); longGradosDecimal.setText("");
}//GEN-LAST:event_gradosMinutosSegundosActionPerformed

    private void decimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decimalActionPerformed
        // TODO add your handling code here:
        
        latGrados.setEditable(false); latGrados.setText("");
        longGrados.setEditable(false); longGrados.setText("");
        latMinutos.setEditable(false); latMinutos.setText("");
        longMinutos.setEditable(false); longMinutos.setText("");
        latSegundos.setEditable(false); latSegundos.setText("");
        longSegundos.setEditable(false); longSegundos.setText("");
        hemisferioLong.setEnabled(false);
        hemisferioLat.setEnabled(false);
        
        latGradosDecimal.setEditable(true);
        longGradosDecimal.setEditable(true);
}//GEN-LAST:event_decimalActionPerformed

    private void obtenerPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obtenerPuntoActionPerformed
        // TODO add your handling code here:
        
        latGradosDecimal.setText("" + controlador.getLibroDeProyectos().getMapa().getObtenerPunto().getLatitudDecimal());
        longGradosDecimal.setText("" + controlador.getLibroDeProyectos().getMapa().getObtenerPunto().getLongitudDecimal());
        controlador.getLibroDeProyectos().getMapa().getObtenerPunto().convertirLat_A_GradMinSeg();
        controlador.getLibroDeProyectos().getMapa().getObtenerPunto().convertirLong_A_GradMinSeg();
        
        DecimalFormat df = new DecimalFormat("##.###");
        
        latGrados.setText("" + controlador.getLibroDeProyectos().getMapa().getObtenerPunto().getLatitudGrados());
        latMinutos.setText("" + controlador.getLibroDeProyectos().getMapa().getObtenerPunto().getLatitudMinutos());
        latSegundos.setText("" + df.format(controlador.getLibroDeProyectos().getMapa().getObtenerPunto().getLatitudSegundos()));
        hemisferioLat.setSelectedItem("" + controlador.getLibroDeProyectos().getMapa().getObtenerPunto().getHemisferioLatitud());
        
        longGrados.setText("" + controlador.getLibroDeProyectos().getMapa().getObtenerPunto().getLongitudGrados());
        longMinutos.setText("" + controlador.getLibroDeProyectos().getMapa().getObtenerPunto().getLongitudMinutos());
        longSegundos.setText("" + df.format(controlador.getLibroDeProyectos().getMapa().getObtenerPunto().getLongitudSegundos()));
        
        hemisferioLong.setSelectedItem("" + controlador.getLibroDeProyectos().getMapa().getObtenerPunto().getHemisferioLongitud());
        
}//GEN-LAST:event_obtenerPuntoActionPerformed

    private void limpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarCamposActionPerformed
        // TODO add your handling code here:
        latGrados.setText("");
        longGrados.setText("");
        latMinutos.setText("");
        longMinutos.setText("");
        latSegundos.setText("");
        longSegundos.setText("");
        latGradosDecimal.setText("");
        longGradosDecimal.setText("");
}//GEN-LAST:event_limpiarCamposActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        
        if(!nombreSitio.getText().equals("")&&!pais.getText().equals("")){
            
            // Si se ingresaron coordenadas geograficas en formato decimal
            if(decimal.isSelected()){
                controlador.getControladorVentanas().editarSitioCoordenadasDecimales(Double.parseDouble(latGradosDecimal.getText()),
                        Double.parseDouble(longGradosDecimal.getText()), sitios.getSelectedItem().toString(),nombreSitio.getText(), direccionSitio.getText(), 
                        pais.getText(), ciudad.getText(), tipoSitio.getSelectedItem().toString());
                this.dispose();
                // Si se ingresaron coordenadas geograficas en formato grados minutos y segundos
            }else if(gradosMinutosSegundos.isSelected()){
                try {
                    DecimalFormat formateador = new DecimalFormat("##.###");
                    Number segundosLatDouble = formateador.parse(latSegundos.getText());
                    Number segundosLongDouble = formateador.parse(longSegundos.getText());
                    
                    controlador.getControladorVentanas().editarSitioCoordenadasGradMinSeg(Integer.parseInt(latGrados.getText()), Integer.parseInt(latMinutos.getText()),
                            (float)segundosLatDouble.doubleValue(),hemisferioLat.getSelectedItem().toString().charAt(0),Integer.parseInt(longGrados.getText()),
                            Integer.parseInt(longMinutos.getText()), (float)segundosLongDouble.doubleValue(), hemisferioLong.getSelectedItem().toString().charAt(0),
                            sitios.getSelectedItem().toString(), nombreSitio.getText(), direccionSitio.getText(), pais.getText(), ciudad.getText(), tipoSitio.getSelectedItem().toString());
                    this.dispose();
                    
                } catch (ParseException ex) {
                    
                }
            }
        }
}//GEN-LAST:event_botonAceptarActionPerformed

    private void botonCanelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCanelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
}//GEN-LAST:event_botonCanelarActionPerformed

    
    private void editarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarButtonActionPerformed
        // TODO add your handling code here:
        if(editarButton.isSelected()){
            cambiarEstadoCampos(true);
        }else{
            cambiarEstadoCampos(false);
        }
    }//GEN-LAST:event_editarButtonActionPerformed

    private void encontrarSitioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encontrarSitioActionPerformed
        // TODO add your handling code here:
        String proyectoPredeterminado = controlador.getLibroDeProyectos().getProyectoPredeterminado();
        LinkedList <Proyecto> proyectos = controlador.getLibroDeProyectos().getProyectos();
        
        for(int i = 0; i < proyectos.size(); i++){
            
            if(proyectos.get(i).getNombre().equals(proyectoPredeterminado)){
                arraySitios = new String [proyectos.get(i).getGrupoSitios().size()];
                for(int j = 0; j < proyectos.get(i).getGrupoSitios().size(); j++){
                    
                    Sitio sitioActual = proyectos.get(i).getGrupoSitios().get(j);
                    if( sitioActual.getNombreSitio().equals(sitios.getSelectedItem().toString())) {
                        
                        nombreSitio.setText(sitioActual.getNombreSitio());
                        direccionSitio.setText(sitioActual.getDireccionSitio());
                        pais.setText(sitioActual.getPais());
                        ciudad.setText(sitioActual.getCiudad());
                        tipoSitio.setSelectedItem("" + sitioActual.getTipoSitio());
                        
                        latGrados.setText("" + sitioActual.getCoordenadaSitio().getLatitudGrados());
                        latMinutos.setText("" + sitioActual.getCoordenadaSitio().getLatitudMinutos());
                        latSegundos.setText("" + sitioActual.getCoordenadaSitio().getLatitudSegundos());
                        longGrados.setText("" + sitioActual.getCoordenadaSitio().getLongitudGrados());
                        longMinutos.setText("" + sitioActual.getCoordenadaSitio().getLongitudMinutos());
                        longSegundos.setText("" + sitioActual.getCoordenadaSitio().getLongitudSegundos());
                        latGradosDecimal.setText("" + sitioActual.getCoordenadaSitio().getLatitudDecimal());
                        longGradosDecimal.setText("" + sitioActual.getCoordenadaSitio().getLongitudDecimal());   
                        
                        hemisferioLat.setSelectedItem("" + sitioActual.getCoordenadaSitio().getHemisferioLatitud());
                        hemisferioLong.setSelectedItem("" + sitioActual.getCoordenadaSitio().getHemisferioLongitud());
                        cambiarEstadoCampos(false);
                    }
                }
            }
        }
    }//GEN-LAST:event_encontrarSitioActionPerformed

    private void cambiarEstadoCampos(boolean status){
        
        //nombreSitio.setEditable(status);
        direccionSitio.setEditable(status);
        pais.setEditable(status);
        ciudad.setEditable(status);
        tipoSitio.setEnabled(status);
        latGrados.setEditable(status);
        latMinutos.setEditable(status);
        latSegundos.setEditable(status);
        longGrados.setEditable(status);
        longMinutos.setEditable(status);
        longSegundos.setEditable(status);
        latGradosDecimal.setEditable(status);
        longGradosDecimal.setEditable(status);
        
        gradosMinutosSegundos.setEnabled(status);
        decimal.setEnabled(status);
        hemisferioLat.setEnabled(status);
        hemisferioLong.setEnabled(status);
        obtenerPunto.setEnabled(status);
        limpiarCampos.setEnabled(status);
    }
    
    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCanelar;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JTextField ciudad;
    private javax.swing.JRadioButton decimal;
    private javax.swing.JTextField direccionSitio;
    private javax.swing.JToggleButton editarButton;
    private javax.swing.JButton encontrarSitio;
    private javax.swing.JRadioButton gradosMinutosSegundos;
    private javax.swing.JComboBox hemisferioLat;
    private javax.swing.JComboBox hemisferioLong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField latGrados;
    private javax.swing.JTextField latGradosDecimal;
    private javax.swing.JTextField latMinutos;
    private javax.swing.JTextField latSegundos;
    private javax.swing.JButton limpiarCampos;
    private javax.swing.JTextField longGrados;
    private javax.swing.JTextField longGradosDecimal;
    private javax.swing.JTextField longMinutos;
    private javax.swing.JTextField longSegundos;
    private javax.swing.JTextField nombreSitio;
    private javax.swing.JButton obtenerPunto;
    private javax.swing.JTextField pais;
    private javax.swing.JComboBox sitios;
    private javax.swing.JComboBox tipoSitio;
    // End of variables declaration//GEN-END:variables
}
