/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VentanaCrearAntena.java
 *
 * Created on 7/09/2011, 07:48:13 PM
 */
package Vista.ventanas.RAN.Components.indoorLink;

import Vista.ventanas.RAN.Components.antenas.*;
import Controlador.ControladorGeneral;
import Libreria.CentrarScreen;
import Modelo.PRO.Proyecto;
import Modelo.RAN.Antena;
import Modelo.RAN.ENodeB;
import Modelo.RAN.Radio;
import Modelo.RAN.TarjetaRadio;
import java.util.LinkedList;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author Usuario
 */
public class VentanaCrearIndoorLink extends javax.swing.JDialog {

    public ControladorGeneral controlador;
    public String nombreRAN;
    public String nombreENodeB;
    public DefaultListModel atenuadoresEnlaceModel;
    
    /** Creates new form VentanaCrearAntena */
    public VentanaCrearIndoorLink(java.awt.Frame parent, boolean modal, ControladorGeneral controlador, String nombreRAN, String nombreENodeB) {
        super(parent, modal); 
        this.controlador = controlador;
        this.nombreRAN = nombreRAN;
        this.nombreENodeB = nombreENodeB;
        initComponents();
        
        String[] arrayEquiposRadio = new String[0];
        String[] arrayAntenas = new String[0];
        String[] arrayAtenuadores = new String[0];
        DefaultListModel atenuadoresModel = new DefaultListModel();
        atenuadoresEnlaceModel = new DefaultListModel();
        
        LinkedList<Proyecto> proyectos = controlador.getLibroDeProyectos().getProyectos();
        String proyectoPredeterminadoActual = controlador.getLibroDeProyectos().getProyectoPredeterminado();
        for(int i=0; i < proyectos.size(); i++){
            //si el proyecto es predeterminado
             if(proyectos.get(i).getNombre().equals(proyectoPredeterminadoActual)){
                 for(int j=0; j < proyectos.get(i).getGrupoRANs().size(); j++){
                     if(proyectos.get(i).getGrupoRANs().get(j).getNombre().equals(nombreRAN)){
                         LinkedList <ENodeB> listaNodos = proyectos.get(i).getGrupoRANs().get(j).getGrupoNodosB();
                         for(int k=0; k < listaNodos.size(); k++){
                             if(listaNodos.get(k).getNombre().equals(nombreENodeB)){
                                 arrayEquiposRadio = new String[listaNodos.get(k).getRadios().size()];
                                 for(int l=0; l < listaNodos.get(k).getRadios().size(); l++){
                                     arrayEquiposRadio[l] = listaNodos.get(k).getRadios().get(l).getNombre();
                                 }    
                                 arrayAntenas = new String[listaNodos.get(k).getAntenas().size()];
                                 for(int l=0; l < listaNodos.get(k).getAntenas().size(); l++){
                                     arrayAntenas[l] = listaNodos.get(k).getAntenas().get(l).getNombreAntena();
                                 } 
                                 
                                 for(int l=0; l < listaNodos.get(k).getAtenuadores().size(); l++){
                                     atenuadoresModel.addElement(listaNodos.get(k).getAtenuadores().get(l).getNombreDispositivo());
                                 } 
                             }
                         }
                     }
                 }
             }
        }
        
        listaAtenuadoresENodeB.setModel(atenuadoresModel);
        equiposRadio.setModel(new DefaultComboBoxModel(arrayEquiposRadio));
        antenas.setModel(new DefaultComboBoxModel(arrayAntenas));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        botonAceptar = new javax.swing.JButton();
        botonCanelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        nombreEnlaceIndoor = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        equiposRadio = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        slotsTarjetas = new javax.swing.JComboBox();
        jPanel6 = new javax.swing.JPanel();
        antenas = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaAtenuadoresLinkActual = new javax.swing.JList();
        jLabel6 = new javax.swing.JLabel();
        agregar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaAtenuadoresENodeB = new javax.swing.JList();
        jLabel9 = new javax.swing.JLabel();
        quitar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nueva Conexión Indoor");
        setIconImage(new ImageIcon("src/Images/iconos16x16/connect-out-add.png").getImage());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setName("jPanel3"); // NOI18N

        jSeparator2.setName("jSeparator2"); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos32x32/connect2-add.png"))); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("Asistente para la creacion de un nueva Conexión Indoor");
        jLabel2.setName("jLabel2"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(232, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setName("jPanel2"); // NOI18N

        botonAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/tick.png"))); // NOI18N
        botonAceptar.setText(" Aceptar");
        botonAceptar.setName("botonAceptar"); // NOI18N
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        botonCanelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/cross-script.png"))); // NOI18N
        botonCanelar.setText(" Cancelar");
        botonCanelar.setName("botonCanelar"); // NOI18N
        botonCanelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCanelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(344, Short.MAX_VALUE)
                .addComponent(botonCanelar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(botonCanelar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel7.setText("Nombre Conexion Indoor:");
        jLabel7.setName("jLabel7"); // NOI18N

        nombreEnlaceIndoor.setName("nombreEnlaceIndoor"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(6, 6, 6)
                .addComponent(nombreEnlaceIndoor, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreEnlaceIndoor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel5.setName("jPanel5"); // NOI18N

        jLabel3.setText("Equipo de Radio:");
        jLabel3.setName("jLabel3"); // NOI18N

        equiposRadio.setName("equiposRadio"); // NOI18N
        equiposRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equiposRadioActionPerformed(evt);
            }
        });

        jLabel4.setText("Tarjeta:");
        jLabel4.setName("jLabel4"); // NOI18N

        slotsTarjetas.setName("slotsTarjetas"); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(equiposRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(slotsTarjetas, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(slotsTarjetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equiposRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(141, 141, 141))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel6.setName("jPanel6"); // NOI18N

        antenas.setName("antenas"); // NOI18N

        jLabel5.setText("Antena:");
        jLabel5.setName("jLabel5"); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(antenas, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(273, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(antenas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel7.setName("jPanel7"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        listaAtenuadoresLinkActual.setBackground(new java.awt.Color(233, 243, 255));
        listaAtenuadoresLinkActual.setName("listaAtenuadoresLinkActual"); // NOI18N
        jScrollPane1.setViewportView(listaAtenuadoresLinkActual);

        jLabel6.setText("Elementos de Atenuacion del eNodeB:");
        jLabel6.setName("jLabel6"); // NOI18N

        agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/resultset_next.png"))); // NOI18N
        agregar.setToolTipText("Agregar Elemento de Atenuacion");
        agregar.setName("agregar"); // NOI18N
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        listaAtenuadoresENodeB.setBackground(new java.awt.Color(255, 245, 245));
        listaAtenuadoresENodeB.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaAtenuadoresENodeB.setToolTipText("");
        listaAtenuadoresENodeB.setMaximumSize(new java.awt.Dimension(1000, 1000));
        listaAtenuadoresENodeB.setMinimumSize(new java.awt.Dimension(100, 0));
        listaAtenuadoresENodeB.setName("listaAtenuadoresENodeB"); // NOI18N
        jScrollPane2.setViewportView(listaAtenuadoresENodeB);

        jLabel9.setText("Elementos de Atenuacion del Enlace Actual:");
        jLabel9.setName("jLabel9"); // NOI18N

        quitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconos16x16/resultset_back.png"))); // NOI18N
        quitar.setToolTipText("Quitar Elemento de Atenuacion");
        quitar.setName("quitar"); // NOI18N
        quitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(121, 121, 121)
                        .addComponent(jLabel9))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quitar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9))
                .addGap(6, 6, 6)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(agregar)
                        .addGap(6, 6, 6)
                        .addComponent(quitar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
       
      try{
            if(!nombreEnlaceIndoor.getText().equals("")&&!equiposRadio.getSelectedItem().toString().equals("")&&!slotsTarjetas.getSelectedItem().toString().equals("")&&
                    !antenas.getSelectedItem().toString().equals("")){

                String[] listaElementosAtenuacion = new String [listaAtenuadoresLinkActual.getModel().getSize()];
                for(int i = 0; i<listaAtenuadoresLinkActual.getModel().getSize(); i++){
                    listaElementosAtenuacion[i] = listaAtenuadoresLinkActual.getModel().getElementAt(i).toString();
                }

                controlador.getControladorVentanas().crearNuevoIndoorLink(nombreEnlaceIndoor.getText(), equiposRadio.getSelectedItem().toString(),
                        Integer.parseInt(slotsTarjetas.getSelectedItem().toString()), antenas.getSelectedItem().toString(), listaElementosAtenuacion ,nombreRAN, nombreENodeB);
                this.dispose();
            }
      }catch(NullPointerException NPE){
          JOptionPane.showMessageDialog(null, "'Existen campos vacio o valores incorrectos'","Error 002: NullPointerException",JOptionPane.ERROR_MESSAGE);
      }
}//GEN-LAST:event_botonAceptarActionPerformed

    private void botonCanelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCanelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
}//GEN-LAST:event_botonCanelarActionPerformed

private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
// TODO add your handling code here:
    try{
        Object elemento = listaAtenuadoresENodeB.getSelectedValue();
        atenuadoresEnlaceModel.addElement(elemento.toString());
        DefaultListModel listModel = (DefaultListModel)listaAtenuadoresENodeB.getModel();
        listModel.removeElement(elemento);
        
        listaAtenuadoresENodeB.setModel(listModel);
        listaAtenuadoresLinkActual.setModel(atenuadoresEnlaceModel);
    }catch(NullPointerException NPE){
        
    }
}//GEN-LAST:event_agregarActionPerformed

private void quitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitarActionPerformed
// TODO add your handling code here:
        try{
        Object elemento = listaAtenuadoresLinkActual.getSelectedValue();
        DefaultListModel listModel1 = (DefaultListModel)listaAtenuadoresENodeB.getModel();
        listModel1.addElement(elemento.toString());
        
        DefaultListModel listModel2 = (DefaultListModel)listaAtenuadoresLinkActual.getModel();
        listModel2.removeElement(elemento);
        
        listaAtenuadoresENodeB.setModel(listModel1);
        listaAtenuadoresLinkActual.setModel(listModel2 );
    }catch(NullPointerException NPE){
        
    }
}//GEN-LAST:event_quitarActionPerformed

private void equiposRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equiposRadioActionPerformed
// TODO add your handling code here:
    String arraySlotsTargetas[] = new String[0];
    LinkedList<Proyecto> proyectos = controlador.getLibroDeProyectos().getProyectos();
        String proyectoPredeterminadoActual = controlador.getLibroDeProyectos().getProyectoPredeterminado();
        for(int i=0; i < proyectos.size(); i++){
            //si el proyecto es predeterminado
             if(proyectos.get(i).getNombre().equals(proyectoPredeterminadoActual)){
                 for(int j=0; j < proyectos.get(i).getGrupoRANs().size(); j++){
                     if(proyectos.get(i).getGrupoRANs().get(j).getNombre().equals(nombreRAN)){
                         LinkedList <ENodeB> listaNodos = proyectos.get(i).getGrupoRANs().get(j).getGrupoNodosB();
                         for(int k=0; k < listaNodos.size(); k++){
                             if(listaNodos.get(k).getNombre().equals(nombreENodeB)){
                                 for(int l=0; l < listaNodos.get(k).getRadios().size(); l++){
                                     TarjetaRadio[] tarjetas = listaNodos.get(k).getRadios().get(l).obtenerTargetasRadioSlotOcupados();
                                     arraySlotsTargetas = new String[tarjetas.length];
                                     for(int m=0; m < tarjetas.length; m++){
                                         try{
                                             arraySlotsTargetas[m]= "" + tarjetas[m].getNumeroSlot();
                                         }catch(ArrayIndexOutOfBoundsException AIBE){
                                             
                                         }
                                     }
                                 } 
                             }
                         }
                     }
                 }
             }
        }
    slotsTarjetas.setModel(new DefaultComboBoxModel(arraySlotsTargetas));
}//GEN-LAST:event_equiposRadioActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JComboBox antenas;
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCanelar;
    private javax.swing.JComboBox equiposRadio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JList listaAtenuadoresENodeB;
    private javax.swing.JList listaAtenuadoresLinkActual;
    private javax.swing.JTextField nombreEnlaceIndoor;
    private javax.swing.JButton quitar;
    private javax.swing.JComboBox slotsTarjetas;
    // End of variables declaration//GEN-END:variables
}
